[scythe]
version = "1"

[[sql]]
name = "main"
engine = "mariadb"
schema = ["../sql/mariadb/schema.sql"]
queries = ["../sql/mariadb/queries/*.sql"]

[[sql.gen]]
backend = "ruby-mysql2"
output = "generated"
