// Auto-generated by scythe. Do not edit.
// Struct definitions extracted from generated/queries.rs.
// Functions removed because sqlx::query!() macros require DATABASE_URL at compile time.
#![allow(dead_code, unused_imports, clippy::all)]

#[derive(Debug, sqlx::FromRow)]
pub struct GetOrdersByUserRow {
    pub id: i32,
    pub total: f32,
    pub notes: Option<String>,
    pub created_at: String,
}

#[derive(Debug, sqlx::FromRow)]
pub struct GetOrderTotalRow {
    pub total_sum: Option<f64>,
}

#[derive(Debug, sqlx::FromRow)]
pub struct GetUserByIdRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
    pub status: String,
    pub created_at: String,
}

#[derive(Debug, sqlx::FromRow)]
pub struct ListActiveUsersRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
}

#[derive(Debug, sqlx::FromRow)]
pub struct SearchUsersRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
}
