[scythe]
version = "1"

[[sql]]
name = "main"
engine = "duckdb"
schema = ["../sql/duckdb/schema.sql"]
queries = ["../sql/duckdb/queries/*.sql"]

[[sql.gen]]
backend = "typescript-duckdb"
output = "generated"
