[scythe]
version = "1"

[[sql]]
name = "main"
engine = "mssql"
schema = ["../sql/mssql/schema.sql"]
queries = ["../sql/mssql/queries/*.sql"]

[[sql.gen]]
backend = "ruby-tiny-tds"
output = "generated"
