use std::fmt::Write;

use scythe_backend::manifest::BackendManifest;
use scythe_backend::naming::{
    enum_type_name, enum_variant_name, fn_name, row_struct_name, to_pascal_case,
};

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::{CodegenBackend, RbsGenerationContext, ResolvedColumn, ResolvedParam};

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/ruby-tiny-tds.toml");

/// Check if a neutral type should not be escaped (numeric or boolean types).
/// Neutral types come from the backend manifest (e.g., "Boolean", "Integer", "Float").
fn is_numeric_or_bool_type(neutral_type: &str) -> bool {
    // Neutral type names are PascalCase or have special forms like "Array<Integer>"
    // Remove container wrappers and check the base type
    let base_type = if neutral_type.contains('<') {
        // Handle Array<T> or similar generic types
        neutral_type.split('<').next().unwrap_or("")
    } else {
        neutral_type
    };

    matches!(
        base_type,
        "Integer"
            | "Boolean"
            | "Int16"
            | "Int32"
            | "Int64"
            | "Float"
            | "Float32"
            | "Float64"
            | "Decimal"
            | "BigDecimal"
            | "Numeric"
            | "Double"
            | "Money"
            | "SmallMoney"
    )
}

/// Check if a neutral type is specifically a boolean.
fn is_bool_type(neutral_type: &str) -> bool {
    let base_type = if neutral_type.contains('<') {
        neutral_type.split('<').next().unwrap_or("")
    } else {
        neutral_type
    };
    base_type == "Boolean"
}

/// Generate a parameter assignment for MSSQL with proper type handling.
/// - Booleans are converted to 0/1 (MSSQL BIT type)
/// - Other numeric types are interpolated directly
/// - Strings are escaped and quoted
/// - `var_access` is used to reference the variable (e.g., "id" or "item[:id]")
fn generate_param_assignment(index: usize, neutral_type: &str, var_access: &str) -> String {
    if is_bool_type(neutral_type) {
        // Convert boolean to 0/1 for MSSQL BIT
        format!("@p{} = #{{{} ? 1 : 0}}", index, var_access)
    } else if is_numeric_or_bool_type(neutral_type) {
        // Other numeric types: interpolate directly
        format!("@p{} = #{{{}}}", index, var_access)
    } else {
        // String types: escape and quote
        format!("@p{} = '#{{client.escape({})}}'", index, var_access)
    }
}

pub struct RubyTinyTdsBackend {
    manifest: BackendManifest,
}

impl RubyTinyTdsBackend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "mssql" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!("ruby-tiny-tds only supports MSSQL, got engine '{}'", engine),
                ));
            }
        }
        let manifest = super::load_or_default_manifest(
            "backends/ruby-tiny-tds/manifest.toml",
            DEFAULT_MANIFEST_TOML,
        )?;
        Ok(Self { manifest })
    }
}

/// Rewrite $1, $2, ... to @p1, @p2, ... for MSSQL.
impl CodegenBackend for RubyTinyTdsBackend {
    fn name(&self) -> &str {
        "ruby-tiny-tds"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["mssql"]
    }

    fn generate_rbs_file(&self, context: &RbsGenerationContext) -> Option<String> {
        Some(super::ruby_rbs::generate_rbs_content(
            context,
            "TinyTds::Client",
        ))
    }

    fn file_header(&self) -> String {
        "# frozen_string_literal: true\n\n# Auto-generated by scythe. Do not edit.\n\nrequire \"tiny_tds\"\n\nmodule Queries"
            .to_string()
    }

    fn file_footer(&self) -> String {
        "end".to_string()
    }

    fn generate_row_struct(
        &self,
        query_name: &str,
        columns: &[ResolvedColumn],
    ) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        let fields = columns
            .iter()
            .map(|c| format!(":{}", c.field_name))
            .collect::<Vec<_>>()
            .join(", ");
        let mut out = String::new();
        let _ = writeln!(out, "  {} = Data.define({})", struct_name, fields);
        Ok(out)
    }

    fn generate_model_struct(
        &self,
        table_name: &str,
        columns: &[ResolvedColumn],
    ) -> Result<String, ScytheError> {
        let name = to_pascal_case(table_name);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = super::rewrite_pg_placeholders(
            &super::clean_sql_with_optional(
                &analyzed.sql,
                &analyzed.optional_params,
                &analyzed.params,
            ),
            |n| format!("@p{n}"),
        );
        let mut out = String::new();

        let param_list = params
            .iter()
            .map(|p| p.field_name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let sep = if param_list.is_empty() { "" } else { ", " };

        // WARNING: TinyTDS does not support parameterized queries natively.
        // We use DECLARE with client.escape() for SQL injection prevention.
        // client.escape() handles quoting/escaping of string values, but callers
        // must ensure non-string types (integers, floats) are validated before passing.
        // Consider using sp_executesql for stronger parameterization if your use case requires it.
        if !matches!(analyzed.command, QueryCommand::Batch) {
            let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
        }

        match &analyzed.command {
            QueryCommand::One | QueryCommand::Opt => {
                if params.is_empty() {
                    let _ = writeln!(out, "    result = client.execute(\"{}\").first", sql);
                } else {
                    // Use string interpolation to build parameterized query
                    let assignments: Vec<String> = params
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            generate_param_assignment(i + 1, &p.neutral_type, &p.field_name)
                        })
                        .collect();
                    let declare = assignments.join(", ");
                    let _ = writeln!(out, "    sql = \"DECLARE {}; {}\"", declare, sql);
                    let _ = writeln!(out, "    result = client.execute(sql).first");
                }
                let _ = writeln!(out, "    return nil if result.nil?");

                let fields = columns
                    .iter()
                    .map(|c| format!("{}: result[\"{}\"]", c.field_name, c.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "    {}.new({})", struct_name, fields);
            }
            QueryCommand::Batch => {
                let batch_fn_name = format!("{}_batch", func_name);
                let _ = writeln!(out, "  def self.{}(client, items)", batch_fn_name);
                let _ = writeln!(out, "    items.each do |item|");
                if params.is_empty() {
                    let _ = writeln!(out, "      client.execute(\"{}\").do", sql);
                } else {
                    let assignments: Vec<String> = params
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            if params.len() == 1 {
                                // Single parameter: interpolate item directly
                                generate_param_assignment(i + 1, &p.neutral_type, "item")
                            } else {
                                // Multiple parameters: access from hash
                                let var_access = format!("item[:{}]", p.field_name);
                                generate_param_assignment(i + 1, &p.neutral_type, &var_access)
                            }
                        })
                        .collect();
                    let declare = assignments.join(", ");
                    let _ = writeln!(out, "      sql = \"DECLARE {}; {}\"", declare, sql);
                    let _ = writeln!(out, "      client.execute(sql).do");
                }
                let _ = writeln!(out, "    end");
                let _ = write!(out, "  end");
                return Ok(out);
            }
            QueryCommand::Many => {
                if params.is_empty() {
                    let _ = writeln!(out, "    results = client.execute(\"{}\")", sql);
                } else {
                    let assignments: Vec<String> = params
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            generate_param_assignment(i + 1, &p.neutral_type, &p.field_name)
                        })
                        .collect();
                    let declare = assignments.join(", ");
                    let _ = writeln!(out, "    sql = \"DECLARE {}; {}\"", declare, sql);
                    let _ = writeln!(out, "    results = client.execute(sql)");
                }
                let _ = writeln!(out, "    results.map do |row|");
                let fields = columns
                    .iter()
                    .map(|c| format!("{}: row[\"{}\"]", c.field_name, c.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "      {}.new({})", struct_name, fields);
                let _ = writeln!(out, "    end");
            }
            QueryCommand::Exec => {
                if params.is_empty() {
                    let _ = writeln!(out, "    client.execute(\"{}\").do", sql);
                } else {
                    let assignments: Vec<String> = params
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            generate_param_assignment(i + 1, &p.neutral_type, &p.field_name)
                        })
                        .collect();
                    let declare = assignments.join(", ");
                    let _ = writeln!(out, "    sql = \"DECLARE {}; {}\"", declare, sql);
                    let _ = writeln!(out, "    client.execute(sql).do");
                }
                let _ = writeln!(out, "    nil");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                if params.is_empty() {
                    let _ = writeln!(out, "    client.execute(\"{}\").affected_rows", sql);
                } else {
                    let assignments: Vec<String> = params
                        .iter()
                        .enumerate()
                        .map(|(i, p)| {
                            generate_param_assignment(i + 1, &p.neutral_type, &p.field_name)
                        })
                        .collect();
                    let declare = assignments.join(", ");
                    let _ = writeln!(out, "    sql = \"DECLARE {}; {}\"", declare, sql);
                    let _ = writeln!(out, "    client.execute(sql).affected_rows");
                }
            }
            QueryCommand::Grouped => unreachable!("handled as Many in codegen"),
        }

        let _ = write!(out, "  end");
        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        let type_name = enum_type_name(&enum_info.sql_name, &self.manifest.naming);
        let mut out = String::new();
        let _ = writeln!(out, "  module {}", type_name);
        for value in &enum_info.values {
            let variant = enum_variant_name(value, &self.manifest.naming);
            let _ = writeln!(out, "    {} = \"{}\"", variant, value);
        }
        let all_values = enum_info
            .values
            .iter()
            .map(|v| enum_variant_name(v, &self.manifest.naming))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    ALL = [{}].freeze", all_values);
        let _ = write!(out, "  end");
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        if composite.fields.is_empty() {
            let _ = writeln!(out, "  {} = Data.define()", name);
        } else {
            let fields = composite
                .fields
                .iter()
                .map(|f| format!(":{}", f.name))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "  {} = Data.define({})", name, fields);
        }
        Ok(out)
    }
}
