use scythe_backend::manifest::BackendManifest;
use scythe_backend::naming::{enum_type_name, enum_variant_name, fn_name, row_struct_name, to_pascal_case};
use std::fmt::Write;

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::{CodegenBackend, GroupedQueryFn, RbsGenerationContext, ResolvedColumn, ResolvedParam};

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/ruby-trilogy.toml");

pub struct RubyTrilogyBackend {
    manifest: BackendManifest,
}

impl RubyTrilogyBackend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "mysql" | "mariadb" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!("ruby-trilogy only supports MySQL, got engine '{}'", engine),
                ));
            }
        }
        let manifest = super::load_or_default_manifest("backends/ruby-trilogy/manifest.toml", DEFAULT_MANIFEST_TOML)?;
        Ok(Self { manifest })
    }
}

/// Map a neutral type to a Ruby type coercion method for trilogy.
fn ruby_coercion(neutral_type: &str) -> &'static str {
    match neutral_type {
        "int16" | "int32" | "int64" => ".to_i",
        "float32" | "float64" => ".to_f",
        "bool" => " == 1",
        _ => "",
    }
}

impl CodegenBackend for RubyTrilogyBackend {
    fn name(&self) -> &str {
        "ruby-trilogy"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["mysql", "mariadb"]
    }

    fn generate_rbs_file(&self, context: &RbsGenerationContext) -> Option<String> {
        Some(super::ruby_rbs::generate_rbs_content(context, "Trilogy"))
    }

    fn file_header(&self) -> String {
        "# frozen_string_literal: true\n\n# Auto-generated by scythe. Do not edit.\n\nmodule Queries".to_string()
    }

    fn file_footer(&self) -> String {
        "end".to_string()
    }

    fn generate_row_struct(&self, query_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        let fields = columns
            .iter()
            .map(|c| format!(":{}", c.field_name))
            .collect::<Vec<_>>()
            .join(", ");
        let mut out = String::new();
        let _ = writeln!(out, "  {} = Data.define({})", struct_name, fields);
        Ok(out)
    }

    fn generate_model_struct(&self, table_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let name = to_pascal_case(table_name);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = super::clean_sql_with_optional(&analyzed.sql, &analyzed.optional_params, &analyzed.params);
        let mut out = String::new();

        let param_list = params
            .iter()
            .map(|p| p.field_name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let sep = if param_list.is_empty() { "" } else { ", " };

        let _param_array = if params.is_empty() {
            "[]".to_string()
        } else {
            format!(
                "[{}]",
                params
                    .iter()
                    .map(|p| p.field_name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };

        match &analyzed.command {
            QueryCommand::One | QueryCommand::Opt => {
                let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
                // Trilogy does not support parameterized queries, so we use string interpolation
                // Replace ? placeholders with #{param_name} for Ruby string interpolation
                // String types need to be quoted for SQL
                let mut sql_interpolated = sql.clone();
                for param in params.iter() {
                    if let Some(pos) = sql_interpolated.find('?') {
                        // Quote strings for SQL, keep numbers unquoted
                        let _param_expr = if param.neutral_type.starts_with("enum::") || param.neutral_type == "string"
                        {
                            format!("\\\"#{{{}}}\\\"\"\n                             ", param.field_name)
                                .replace("\n                             ", "")
                                .replace("\\\"", "'")
                        } else {
                            format!("#{{{}}}", param.field_name)
                        };

                        if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("'#{{{}}}'", param.field_name));
                        } else {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("#{{{}}}", param.field_name));
                        }
                    }
                }

                if params.is_empty() {
                    let _ = writeln!(out, "    results = client.query(\"{}\")", sql);
                } else {
                    let _ = writeln!(out, "    results = client.query(\"{}\")", sql_interpolated);
                }
                let _ = writeln!(out, "    row = results.first");
                let _ = writeln!(out, "    return nil if row.nil?");

                let fields = columns
                    .iter()
                    .enumerate()
                    .map(|(i, c)| {
                        let coercion = ruby_coercion(&c.neutral_type);
                        if c.nullable {
                            format!("{}: row[{}]&.then {{ |v| v{} }}", c.field_name, i, coercion)
                        } else {
                            format!("{}: row[{}]{}", c.field_name, i, coercion)
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "    {}.new({})", struct_name, fields);
            }
            QueryCommand::Batch => {
                let batch_fn_name = format!("{}_batch", func_name);
                // Batch writes its own function signature (not the outer one)
                let _ = writeln!(out, "  def self.{}(client, items)", batch_fn_name);
                let _ = writeln!(out, "    items.each do |item|");
                if params.is_empty() {
                    let _ = writeln!(out, "      client.query(\"{}\")", sql);
                } else if params.len() > 1 {
                    // Multiple params: destructure from tuple/array
                    let mut sql_with_params = sql.clone();
                    for (i, param) in params.iter().enumerate() {
                        if let Some(pos) = sql_with_params.find('?') {
                            let item_expr = format!("item[{}]", i);
                            if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                                sql_with_params.replace_range(pos..pos + 1, &format!("'#{{{}}}'", item_expr));
                            } else {
                                sql_with_params.replace_range(pos..pos + 1, &format!("#{{{}}}", item_expr));
                            }
                        }
                    }
                    let _ = writeln!(out, "      client.query(\"{}\")", sql_with_params);
                } else {
                    // Single param
                    let mut sql_with_param = sql.clone();
                    if let Some(pos) = sql_with_param.find('?') {
                        let param = &params[0];
                        if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                            sql_with_param.replace_range(pos..pos + 1, "'#{item}'");
                        } else {
                            sql_with_param.replace_range(pos..pos + 1, "#{item}");
                        }
                    }
                    let _ = writeln!(out, "      client.query(\"{}\")", sql_with_param);
                }
                let _ = writeln!(out, "    end");
                let _ = write!(out, "  end");
                return Ok(out);
            }
            QueryCommand::Many => {
                let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
                // Replace ? placeholders with #{param_name} for Ruby string interpolation
                // String types need to be quoted for SQL
                let mut sql_interpolated = sql.clone();
                for param in params.iter() {
                    if let Some(pos) = sql_interpolated.find('?') {
                        if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("'#{{{}}}'", param.field_name));
                        } else {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("#{{{}}}", param.field_name));
                        }
                    }
                }

                if params.is_empty() {
                    let _ = writeln!(out, "    results = client.query(\"{}\")", sql);
                } else {
                    let _ = writeln!(out, "    results = client.query(\"{}\")", sql_interpolated);
                }
                let _ = writeln!(out, "    results.map do |row|");
                let fields = columns
                    .iter()
                    .enumerate()
                    .map(|(i, c)| {
                        let coercion = ruby_coercion(&c.neutral_type);
                        if c.nullable {
                            format!("{}: row[{}]&.then {{ |v| v{} }}", c.field_name, i, coercion)
                        } else {
                            format!("{}: row[{}]{}", c.field_name, i, coercion)
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(out, "      {}.new({})", struct_name, fields);
                let _ = writeln!(out, "    end");
            }
            QueryCommand::Exec => {
                let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
                // Replace ? placeholders with #{param_name} for Ruby string interpolation
                // String types need to be quoted for SQL
                let mut sql_interpolated = sql.clone();
                for param in params.iter() {
                    if let Some(pos) = sql_interpolated.find('?') {
                        if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("'#{{{}}}'", param.field_name));
                        } else {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("#{{{}}}", param.field_name));
                        }
                    }
                }

                if params.is_empty() {
                    let _ = writeln!(out, "    client.query(\"{}\")", sql);
                } else {
                    let _ = writeln!(out, "    client.query(\"{}\")", sql_interpolated);
                }
                let _ = writeln!(out, "    nil");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
                // Replace ? placeholders with #{param_name} for Ruby string interpolation
                // String types need to be quoted for SQL
                let mut sql_interpolated = sql.clone();
                for param in params.iter() {
                    if let Some(pos) = sql_interpolated.find('?') {
                        if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("'#{{{}}}'", param.field_name));
                        } else {
                            sql_interpolated.replace_range(pos..pos + 1, &format!("#{{{}}}", param.field_name));
                        }
                    }
                }

                if params.is_empty() {
                    let _ = writeln!(out, "    client.query(\"{}\")", sql);
                } else {
                    let _ = writeln!(out, "    client.query(\"{}\")", sql_interpolated);
                }
                let _ = writeln!(out, "    client.affected_rows");
            }
            QueryCommand::Grouped => unreachable!("handled by generate_grouped_query_fn"),
        }

        let _ = write!(out, "  end");
        Ok(out)
    }

    fn generate_grouped_structs(
        &self,
        parent_struct_name: &str,
        child_struct_name: &str,
        parent_columns: &[ResolvedColumn],
        child_columns: &[ResolvedColumn],
        _key_column: &str,
    ) -> Result<String, ScytheError> {
        Ok(super::ruby_rbs::generate_grouped_structs_ruby(
            parent_struct_name,
            child_struct_name,
            parent_columns,
            child_columns,
        ))
    }

    fn generate_grouped_query_fn(&self, request: &GroupedQueryFn<'_>) -> Result<String, ScytheError> {
        let analyzed = request.analyzed;
        let parent_struct_name = request.parent_struct_name;
        let child_struct_name = request.child_struct_name;
        let all_columns = request.all_columns;
        let parent_columns = request.parent_columns;
        let child_columns = request.child_columns;
        let params = request.params;
        let key_column = request.key_column;

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = super::clean_sql_with_optional(&analyzed.sql, &analyzed.optional_params, &analyzed.params);

        let param_list = params
            .iter()
            .map(|p| p.field_name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let sep = if param_list.is_empty() { "" } else { ", " };

        // Apply Ruby string interpolation for any ? placeholders (trilogy style).
        let mut sql_interpolated = sql.clone();
        for param in params.iter() {
            if let Some(pos) = sql_interpolated.find('?') {
                if param.neutral_type.starts_with("enum::") || param.neutral_type == "string" {
                    sql_interpolated.replace_range(pos..pos + 1, &format!("'#{{{}}}'", param.field_name));
                } else {
                    sql_interpolated.replace_range(pos..pos + 1, &format!("#{{{}}}", param.field_name));
                }
            }
        }
        let final_sql = if params.is_empty() { sql } else { sql_interpolated };

        let key_idx = all_columns.iter().position(|c| c.name == key_column).unwrap_or(0);
        let key_neutral_type = all_columns
            .iter()
            .find(|c| c.name == key_column)
            .map(|c| c.neutral_type.as_str())
            .unwrap_or("string");
        let key_coercion = ruby_coercion(key_neutral_type);

        let mut out = String::new();
        let _ = writeln!(out, "  def self.{}(client{}{})", func_name, sep, param_list);
        let _ = writeln!(out, "    results = client.query(\"{}\")", final_sql);
        let _ = writeln!(out, "    _index = {{}}");
        let _ = writeln!(out, "    _entries = []");
        let _ = writeln!(out, "    results.each do |row|");
        let _ = writeln!(out, "      key = row[{}]{}", key_idx, key_coercion);
        let _ = writeln!(out, "      unless _index.key?(key)");
        let _ = writeln!(out, "        _index[key] = _entries.size");
        let _ = writeln!(out, "        _entries << {{");
        for col in parent_columns {
            let col_idx = all_columns.iter().position(|c| c.name == col.name).unwrap_or(0);
            let coercion = ruby_coercion(&col.neutral_type);
            if col.nullable && !coercion.is_empty() {
                let _ = writeln!(
                    out,
                    "          {}: row[{}]&.then {{ |v| v{} }},",
                    col.field_name, col_idx, coercion
                );
            } else {
                let _ = writeln!(out, "          {}: row[{}]{},", col.field_name, col_idx, coercion);
            }
        }
        let _ = writeln!(out, "          children: []");
        let _ = writeln!(out, "        }}");
        let _ = writeln!(out, "      end");
        let _ = writeln!(
            out,
            "      _entries[_index[key]][:children] << {}.new(",
            child_struct_name
        );
        for col in child_columns {
            let col_idx = all_columns.iter().position(|c| c.name == col.name).unwrap_or(0);
            let coercion = ruby_coercion(&col.neutral_type);
            if col.nullable && !coercion.is_empty() {
                let _ = writeln!(
                    out,
                    "        {}: row[{}]&.then {{ |v| v{} }},",
                    col.field_name, col_idx, coercion
                );
            } else {
                let _ = writeln!(out, "        {}: row[{}]{},", col.field_name, col_idx, coercion);
            }
        }
        let _ = writeln!(out, "      )");
        let _ = writeln!(out, "    end");
        let _ = writeln!(out, "    _entries.map {{ |e| {}.new(**e) }}", parent_struct_name);
        let _ = write!(out, "  end");

        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        let type_name = enum_type_name(&enum_info.sql_name, &self.manifest.naming);
        let mut out = String::new();
        let _ = writeln!(out, "  module {}", type_name);
        for value in &enum_info.values {
            let variant = enum_variant_name(value, &self.manifest.naming);
            let _ = writeln!(out, "    {} = \"{}\"", variant, value);
        }
        let all_values = enum_info
            .values
            .iter()
            .map(|v| enum_variant_name(v, &self.manifest.naming))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "    ALL = [{}].freeze", all_values);
        let _ = write!(out, "  end");
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        if composite.fields.is_empty() {
            let _ = writeln!(out, "  {} = Data.define()", name);
        } else {
            let fields = composite
                .fields
                .iter()
                .map(|f| format!(":{}", f.name))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "  {} = Data.define({})", name, fields);
        }
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use scythe_core::analyzer::{AnalyzedColumn, AnalyzedQuery, GroupByConfig};
    use scythe_core::parser::QueryCommand;

    fn make_grouped_query() -> AnalyzedQuery {
        let parent_cols = vec![
            AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
            },
            AnalyzedColumn {
                name: "name".to_string(),
                neutral_type: "string".to_string(),
                nullable: false,
            },
            AnalyzedColumn {
                name: "email".to_string(),
                neutral_type: "string".to_string(),
                nullable: false,
            },
        ];
        let child_cols = vec![
            AnalyzedColumn {
                name: "order_id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
            },
            AnalyzedColumn {
                name: "total".to_string(),
                neutral_type: "decimal".to_string(),
                nullable: true,
            },
            AnalyzedColumn {
                name: "order_date".to_string(),
                neutral_type: "datetime".to_string(),
                nullable: false,
            },
        ];
        let all_cols = [parent_cols.clone(), child_cols.clone()].concat();
        AnalyzedQuery {
            name: "GetUsersWithOrders".to_string(),
            command: QueryCommand::Grouped,
            sql: "SELECT u.id, u.name, u.email, o.id AS order_id, o.total, o.created_at AS order_date\nFROM users u\nJOIN orders o ON o.user_id = u.id".to_string(),
            columns: all_cols,
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: Some(GroupByConfig {
                table: "users".to_string(),
                key_column: "id".to_string(),
                parent_columns: parent_cols,
                child_columns: child_cols,
            }),
            custom: vec![],
        }
    }

    #[test]
    fn test_grouped_ruby_trilogy_structs() {
        let backend = RubyTrilogyBackend::new("mysql").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        let row_struct = result.row_struct.as_deref().unwrap();
        assert!(
            row_struct.contains("GetUsersWithOrdersChildRow = Data.define(:order_id, :total, :order_date)"),
            "missing child struct; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("GetUsersWithOrdersRow = Data.define(:id, :name, :email, :children)"),
            "missing parent struct; got:\n{row_struct}"
        );
        let child_pos = row_struct.find("GetUsersWithOrdersChildRow").unwrap();
        let parent_pos = row_struct.find("GetUsersWithOrdersRow = Data.define").unwrap();
        assert!(child_pos < parent_pos, "child struct must appear before parent struct");
    }

    #[test]
    fn test_grouped_ruby_trilogy_query_fn() {
        let backend = RubyTrilogyBackend::new("mysql").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        let query_fn = result.query_fn.as_deref().unwrap();
        assert!(
            query_fn.contains("def self.get_users_with_orders(client)"),
            "missing fn; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("client.query("),
            "must use client.query; got:\n{query_fn}"
        );
        // Positional index access
        assert!(
            query_fn.contains("key = row[0]"),
            "must access key by index; got:\n{query_fn}"
        );
        assert!(query_fn.contains("_index = {}"), "must use _index; got:\n{query_fn}");
        assert!(
            query_fn.contains("GetUsersWithOrdersChildRow.new("),
            "must construct child struct; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("GetUsersWithOrdersRow.new(**e)"),
            "must fold into parent; got:\n{query_fn}"
        );
    }
}
