use scythe_backend::manifest::BackendManifest;
use scythe_backend::naming::{
    enum_type_name, enum_variant_name, fn_name, row_struct_name, to_camel_case, to_pascal_case,
};
use scythe_backend::types::resolve_type;
use std::fmt::Write;

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::{CodegenBackend, GroupedQueryFn, ResolvedColumn, ResolvedParam};
use crate::backends::typescript_common::{
    TsFieldCase, TsRowShape, TsRowType, escape_ts_template_literal, generate_grouped_interface_structs,
    generate_ts_grouped_fold_body, generate_ts_interface_row_struct_with_base, generate_ts_many_row_remap,
    generate_ts_one_row_remap, generate_ts_union_row_struct, generate_zod_enum, generate_zod_grouped_structs,
    generate_zod_row_struct, generate_zod_union_row_struct, parse_bool_option, reject_unknown_options,
};
use crate::singularize;

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/typescript-mysql2.toml");

pub struct TypescriptMysql2Backend {
    manifest: BackendManifest,
    row_type: TsRowType,
    /// Emit outer-join nullability as a discriminated union instead of
    /// independent per-column optionals. Opt-in: the flat shape stays the
    /// default and the cross-target shape.
    outer_join_unions: bool,
    /// When true, only emit type definitions (interfaces/Zod schemas, enums,
    /// composites) — no query functions. `Pool` is dropped from the driver
    /// import since nothing names it any more. `RowDataPacket` survives only
    /// under `field_case = "snake_case"`, where every generated row type
    /// still extends/intersects it; under `Camel` the row types drop that
    /// base and the only remaining references are in the query functions
    /// `structs_only` suppresses, so the driver import goes away entirely.
    /// See [`CodegenBackend::file_header`].
    structs_only: bool,
    /// Under `Camel`, declared row types stop extending/intersecting
    /// `RowDataPacket` (its `[column: string]: any` index signature would
    /// keep accepting the driver's raw snake_case keys structurally, even
    /// on a type that declares only camelCase fields -- defeating the point
    /// of renaming them), and `:one`/`:opt`/`:many` fetch through bare
    /// `RowDataPacket` and reconstruct the row field by field instead of
    /// trusting a `pool.execute<StructName[]>` generic -- see
    /// [`generate_ts_one_row_remap`]/[`generate_ts_many_row_remap`]. `Snake`
    /// (the default) is unchanged.
    field_case: TsFieldCase,
}

impl TypescriptMysql2Backend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "mysql" | "mariadb" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!("typescript-mysql2 only supports MySQL/MariaDB, got engine '{}'", engine),
                ));
            }
        }
        let manifest = super::parse_manifest(DEFAULT_MANIFEST_TOML)?;
        Ok(Self {
            manifest,
            row_type: TsRowType::default(),
            outer_join_unions: false,
            structs_only: false,
            field_case: TsFieldCase::default(),
        })
    }
}

impl CodegenBackend for TypescriptMysql2Backend {
    fn name(&self) -> &str {
        "typescript-mysql2"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn manifest_mut(&mut self) -> &mut scythe_backend::manifest::BackendManifest {
        &mut self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["mysql", "mariadb"]
    }

    fn file_header(&self) -> String {
        let mut types: Vec<&str> = Vec::new();
        // `Pool` is only ever named by a query function signature.
        if !self.structs_only {
            types.push("Pool");
        }
        // `RowDataPacket` has two independent referrers, and `noUnusedLocals`
        // fails the generated file if neither is present. Under `Snake` the
        // declared row types extend/intersect it, so it is always used.
        // Under `Camel` they drop that base (see `generate_row_struct`),
        // leaving the `pool.execute<RowDataPacket[]>` fetch in the query
        // functions as the only reference — which `structs_only` removes.
        if self.field_case == TsFieldCase::Snake || !self.structs_only {
            types.push("RowDataPacket");
        }

        let mut header = "/** Auto-generated by scythe. Do not edit. */\n".to_string();
        let mut imports = String::new();
        if !types.is_empty() {
            let _ = writeln!(
                imports,
                "import type {{ {} }} from \"mysql2/promise\";",
                types.join(", ")
            );
        }
        if self.row_type == TsRowType::Zod {
            imports.push_str("import { z } from \"zod\";\n");
        }
        if !imports.is_empty() {
            header.push('\n');
            header.push_str(&imports);
        }
        header
    }

    fn generate_row_struct(&self, query_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        // Under Camel, the declared row type must not extend/intersect
        // RowDataPacket -- see the `field_case` field doc for why -- so
        // there is also no bridging `{struct_name}Packet` type to generate:
        // `:one`/`:opt`/`:many` fetch through bare `RowDataPacket` directly
        // in that mode (mirroring what the `:grouped` fold already does
        // unconditionally), so nothing needs a per-query Packet alias.
        let base = match self.field_case {
            TsFieldCase::Snake => Some("RowDataPacket"),
            TsFieldCase::Camel => None,
        };
        if self.row_type == TsRowType::Zod {
            if self.outer_join_unions {
                let mut out = generate_zod_union_row_struct(&struct_name, query_name, columns);
                let Some(base) = base else {
                    return Ok(out);
                };
                let _ = writeln!(out);
                let _ = writeln!(out);
                // `interface extends` cannot extend a union, so use an
                // intersection type alias instead; it stays valid even
                // when there's no discriminant and the schema collapses
                // back to a plain object.
                let _ = write!(out, "export type {struct_name}Packet = {base} & {struct_name};");
                return Ok(out);
            }
            let mut out = generate_zod_row_struct(&struct_name, query_name, columns);
            let Some(base) = base else {
                return Ok(out);
            };
            let _ = writeln!(out);
            let _ = writeln!(out);
            let _ = write!(
                out,
                "export interface {struct_name}Packet extends {base}, {struct_name} {{}}"
            );
            return Ok(out);
        }
        if self.outer_join_unions {
            return Ok(generate_ts_union_row_struct(&struct_name, query_name, columns, base));
        }
        Ok(generate_ts_interface_row_struct_with_base(
            &struct_name,
            query_name,
            columns,
            base,
        ))
    }

    fn generate_model_struct(&self, table_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let singular = singularize(table_name);
        let name = to_pascal_case(&singular);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        if self.structs_only {
            return Ok(String::new());
        }

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let mut out = String::new();

        let sql = escape_ts_template_literal(&super::clean_sql_with_optional(
            &analyzed.sql,
            &analyzed.optional_params,
            &analyzed.params,
        ));

        let write_fn_sig = |out: &mut String, name: &str, sig_params: &[(String, String)], ret: &str| {
            let params_inline = sig_params
                .iter()
                .map(|(n, t)| format!("{n}: {t}"))
                .collect::<Vec<_>>()
                .join(", ");
            let oneliner = format!("export async function {}({}): {} {{", name, params_inline, ret);
            if oneliner.len() <= 80 {
                let _ = writeln!(out, "{}", oneliner);
            } else {
                let _ = writeln!(out, "export async function {}(", name);
                for (n, t) in sig_params {
                    let _ = writeln!(out, "\t{}: {},", n, t);
                }
                let _ = writeln!(out, "): {} {{", ret);
            }
        };

        let query_sig_params: Vec<(String, String)> = std::iter::once(("pool".to_string(), "Pool".to_string()))
            .chain(params.iter().map(|p| (p.field_name.clone(), p.full_type.clone())))
            .collect();

        let param_array = if params.is_empty() {
            String::new()
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            format!(", [{}]", args.join(", "))
        };

        // Under Camel there is no Packet type to name (see generate_row_struct):
        // the fetch always trusts bare RowDataPacket instead, then remaps.
        let query_type = match self.field_case {
            TsFieldCase::Snake if self.row_type == TsRowType::Zod => format!("{struct_name}Packet"),
            TsFieldCase::Snake => struct_name.to_string(),
            TsFieldCase::Camel => "RowDataPacket".to_string(),
        };

        match &analyzed.command {
            QueryCommand::One | QueryCommand::Opt => {
                let _ = writeln!(out, "/** Fetch a single {} or null. */", struct_name);
                let ret = format!("Promise<{} | null>", struct_name);
                write_fn_sig(&mut out, &func_name, &query_sig_params, &ret);
                let _ = writeln!(out, "\tconst [rows] = await pool.execute<{}[]>(", query_type);
                let _ = writeln!(out, "\t\t`{}`{},", sql, param_array);
                let _ = writeln!(out, "\t);");
                match self.field_case {
                    TsFieldCase::Snake => {
                        let _ = writeln!(out, "\treturn rows[0] ?? null;");
                    }
                    TsFieldCase::Camel => {
                        let _ = writeln!(out, "\tconst row = rows[0];");
                        out.push_str(&generate_ts_one_row_remap(
                            columns,
                            TsRowShape::from_outer_join_unions(self.outer_join_unions),
                            |name, ty| format!("row.{name} as {ty}"),
                        ));
                    }
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::Batch => {
                let batch_fn_name = format!("{}Batch", func_name);
                if params.len() > 1 {
                    let params_type_name = format!("{}BatchParams", struct_name);
                    let _ = writeln!(out, "/** Params for {} batch operation. */", struct_name);
                    let _ = writeln!(out, "export interface {} {{", params_type_name);
                    for p in params {
                        let _ = writeln!(out, "\t{}: {};", p.field_name, p.full_type);
                    }
                    let _ = writeln!(out, "}}");
                    let _ = writeln!(out);
                    let _ = writeln!(out, "/** Execute {} for each item in the batch. */", analyzed.name);
                    let batch_sig_params = vec![
                        ("pool".to_string(), "Pool".to_string()),
                        ("items".to_string(), format!("{}[]", params_type_name)),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "Promise<void>");
                    let _ = writeln!(out, "\tconst conn = await pool.getConnection();");
                    let _ = writeln!(out, "\ttry {{");
                    let _ = writeln!(out, "\t\tawait conn.beginTransaction();");
                    let _ = writeln!(out, "\t\tfor (const item of items) {{");
                    let args: Vec<String> = params.iter().map(|p| format!("item.{}", p.field_name)).collect();
                    let _ = writeln!(out, "\t\t\tawait conn.execute(");
                    let args_str = args.join(", ");
                    let _ = writeln!(out, "\t\t\t\t`{}`, [{}],", sql, args_str);
                    let _ = writeln!(out, "\t\t\t);");
                    let _ = writeln!(out, "\t\t}}");
                    let _ = writeln!(out, "\t\tawait conn.commit();");
                    let _ = writeln!(out, "\t}} catch (error) {{");
                    let _ = writeln!(out, "\t\tawait conn.rollback();");
                    let _ = writeln!(out, "\t\tthrow error;");
                    let _ = writeln!(out, "\t}} finally {{");
                    let _ = writeln!(out, "\t\tconn.release();");
                    let _ = writeln!(out, "\t}}");
                    let _ = write!(out, "}}");
                } else if params.len() == 1 {
                    let _ = writeln!(out, "/** Execute {} for each item in the batch. */", analyzed.name);
                    let batch_sig_params = vec![
                        ("pool".to_string(), "Pool".to_string()),
                        ("items".to_string(), format!("{}[]", params[0].full_type)),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "Promise<void>");
                    let _ = writeln!(out, "\tconst conn = await pool.getConnection();");
                    let _ = writeln!(out, "\ttry {{");
                    let _ = writeln!(out, "\t\tawait conn.beginTransaction();");
                    let _ = writeln!(out, "\t\tfor (const item of items) {{");
                    let _ = writeln!(out, "\t\t\tawait conn.execute(`{}`, [item]);", sql);
                    let _ = writeln!(out, "\t\t}}");
                    let _ = writeln!(out, "\t\tawait conn.commit();");
                    let _ = writeln!(out, "\t}} catch (error) {{");
                    let _ = writeln!(out, "\t\tawait conn.rollback();");
                    let _ = writeln!(out, "\t\tthrow error;");
                    let _ = writeln!(out, "\t}} finally {{");
                    let _ = writeln!(out, "\t\tconn.release();");
                    let _ = writeln!(out, "\t}}");
                    let _ = write!(out, "}}");
                } else {
                    let _ = writeln!(out, "/** Execute {} for each item in the batch. */", analyzed.name);
                    let batch_sig_params = vec![
                        ("pool".to_string(), "Pool".to_string()),
                        ("count".to_string(), "number".to_string()),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "Promise<void>");
                    let _ = writeln!(out, "\tconst conn = await pool.getConnection();");
                    let _ = writeln!(out, "\ttry {{");
                    let _ = writeln!(out, "\t\tawait conn.beginTransaction();");
                    let _ = writeln!(out, "\t\tfor (let i = 0; i < count; i++) {{");
                    let _ = writeln!(out, "\t\t\tawait conn.execute(`{}`);", sql);
                    let _ = writeln!(out, "\t\t}}");
                    let _ = writeln!(out, "\t\tawait conn.commit();");
                    let _ = writeln!(out, "\t}} catch (error) {{");
                    let _ = writeln!(out, "\t\tawait conn.rollback();");
                    let _ = writeln!(out, "\t\tthrow error;");
                    let _ = writeln!(out, "\t}} finally {{");
                    let _ = writeln!(out, "\t\tconn.release();");
                    let _ = writeln!(out, "\t}}");
                    let _ = write!(out, "}}");
                }
            }
            QueryCommand::Many => {
                let _ = writeln!(out, "/** Fetch all {} rows. */", struct_name);
                let ret = format!("Promise<{}[]>", struct_name);
                write_fn_sig(&mut out, &func_name, &query_sig_params, &ret);
                let _ = writeln!(out, "\tconst [rows] = await pool.execute<{}[]>(", query_type);
                let _ = writeln!(out, "\t\t`{}`{},", sql, param_array);
                let _ = writeln!(out, "\t);");
                match self.field_case {
                    TsFieldCase::Snake => {
                        let _ = writeln!(out, "\treturn rows;");
                    }
                    TsFieldCase::Camel => {
                        out.push_str(&generate_ts_many_row_remap(
                            columns,
                            TsRowShape::from_outer_join_unions(self.outer_join_unions),
                            |name, ty| format!("row.{name} as {ty}"),
                        ));
                    }
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::Exec => {
                let _ = writeln!(out, "/** Execute a query returning no rows. */");
                write_fn_sig(&mut out, &func_name, &query_sig_params, "Promise<void>");
                let _ = writeln!(out, "\tawait pool.execute(");
                let _ = writeln!(out, "\t\t`{}`{},", sql, param_array);
                let _ = writeln!(out, "\t);");
                let _ = write!(out, "}}");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                let _ = writeln!(out, "/** Execute a query and return the number of affected rows. */");
                write_fn_sig(&mut out, &func_name, &query_sig_params, "Promise<number>");
                let _ = writeln!(out, "\tconst [result] = await pool.execute(");
                let _ = writeln!(out, "\t\t`{}`{},", sql, param_array);
                let _ = writeln!(out, "\t);");
                let _ = writeln!(out, "\treturn (result as {{ affectedRows: number }}).affectedRows;");
                let _ = write!(out, "}}");
            }
            QueryCommand::Grouped => {
                unreachable!("Grouped command is routed through generate_grouped_query_fn, not generate_query_fn")
            }
        }

        Ok(out)
    }

    fn generate_grouped_structs(
        &self,
        parent_struct_name: &str,
        child_struct_name: &str,
        parent_columns: &[ResolvedColumn],
        child_columns: &[ResolvedColumn],
        _key_column: &str,
    ) -> Result<String, ScytheError> {
        if self.row_type == TsRowType::Zod {
            return Ok(generate_zod_grouped_structs(
                child_struct_name,
                parent_struct_name,
                parent_columns,
                child_columns,
            ));
        }
        Ok(generate_grouped_interface_structs(
            child_struct_name,
            parent_struct_name,
            parent_columns,
            child_columns,
        ))
    }

    fn generate_grouped_query_fn(&self, request: &GroupedQueryFn<'_>) -> Result<String, ScytheError> {
        let analyzed = request.analyzed;
        let parent_struct_name = request.parent_struct_name;
        let child_struct_name = request.child_struct_name;
        let parent_columns = request.parent_columns;
        let child_columns = request.child_columns;
        let params = request.params;
        let key_column = request.key_column;

        if self.structs_only {
            return Ok(String::new());
        }

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = escape_ts_template_literal(&super::clean_sql_with_optional(
            &analyzed.sql,
            &analyzed.optional_params,
            &analyzed.params,
        ));

        let param_list = params
            .iter()
            .map(|p| format!("{}: {}", p.field_name, p.full_type))
            .collect::<Vec<_>>()
            .join(", ");
        let inline_params = if params.is_empty() {
            "pool: Pool".to_string()
        } else {
            format!("pool: Pool, {}", param_list)
        };
        let ret = format!("Promise<{parent_struct_name}[]>");

        let mut out = String::new();
        let oneliner = format!("export async function {func_name}({inline_params}): {ret} {{");
        if oneliner.len() <= 80 {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "{oneliner}");
        } else {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "export async function {func_name}(");
            let _ = writeln!(out, "\tpool: Pool,");
            for p in params {
                let _ = writeln!(out, "\t{}: {},", p.field_name, p.full_type);
            }
            let _ = writeln!(out, "): {ret} {{");
        }

        if params.is_empty() {
            let _ = writeln!(
                out,
                "\tconst [flatRows] = await pool.execute<RowDataPacket[]>(`{sql}`);"
            );
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            let _ = writeln!(
                out,
                "\tconst [flatRows] = await pool.execute<RowDataPacket[]>(`{sql}`, [{}]);",
                args.join(", ")
            );
        }

        let fold = generate_ts_grouped_fold_body(
            parent_struct_name,
            child_struct_name,
            parent_columns,
            child_columns,
            key_column,
            |name, _ty| format!("row.{name}"),
        );
        out.push_str(&fold);
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        let type_name = enum_type_name(&enum_info.sql_name, &self.manifest.naming);
        if self.row_type == TsRowType::Zod {
            return Ok(generate_zod_enum(&type_name, &enum_info.values));
        }
        let mut out = String::new();
        let _ = writeln!(out, "export enum {} {{", type_name);
        for value in &enum_info.values {
            let variant = enum_variant_name(value, &self.manifest.naming);
            let _ = writeln!(out, "\t{} = \"{}\",", variant, value);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        let _ = writeln!(out, "/** Composite type {}. */", composite.sql_name);
        let _ = writeln!(out, "export interface {} {{", name);
        for field in &composite.fields {
            let ts_type = resolve_type(&field.neutral_type, &self.manifest, false)
                .map(|t| t.into_owned())
                .map_err(|e| {
                    ScytheError::new(ErrorCode::InternalError, format!("composite field type error: {}", e))
                })?;
            let _ = writeln!(out, "\t{}: {};", to_camel_case(&field.name), ts_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn apply_options(&mut self, options: &std::collections::HashMap<String, String>) -> Result<(), ScytheError> {
        reject_unknown_options(
            &["row_type", "outer_join_unions", "structs_only", "field_case"],
            options,
        )?;

        if let Some(value) = options.get("row_type") {
            self.row_type = TsRowType::from_option(value)?;
        }
        if let Some(value) = options.get("outer_join_unions") {
            self.outer_join_unions = parse_bool_option("outer_join_unions", value)?;
        }
        if let Some(value) = options.get("structs_only") {
            self.structs_only = parse_bool_option("structs_only", value)?;
        }
        if let Some(value) = options.get("field_case") {
            self.field_case = TsFieldCase::from_option(value)?;
            self.manifest.naming.field_case = value.clone();
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::TypescriptMysql2Backend;
    use crate::backend_trait::CodegenBackend;
    use scythe_core::analyzer::{AnalyzedColumn, AnalyzedParam, AnalyzedQuery, GroupByConfig};
    use scythe_core::parser::QueryCommand;

    fn discriminated_join_columns() -> Vec<crate::backend_trait::ResolvedColumn> {
        use crate::backend_trait::ResolvedColumn;
        vec![
            ResolvedColumn {
                name: "id".to_string(),
                field_name: "id".to_string(),
                lang_type: "number".to_string(),
                full_type: "number".to_string(),
                neutral_type: "int32".to_string(),
                sql_type: "int".to_string(),
                nullable: false,
                join_group: None,
                nullable_before_join: false,
            },
            ResolvedColumn {
                name: "total".to_string(),
                field_name: "total".to_string(),
                lang_type: "string".to_string(),
                full_type: "string | null".to_string(),
                neutral_type: "decimal".to_string(),
                sql_type: "decimal".to_string(),
                nullable: true,
                join_group: Some("o".to_string()),
                nullable_before_join: false,
            },
        ]
    }

    /// Before the fix, `row_type = "zod"` returned before the
    /// `outer_join_unions` branch was ever reached, silently discarding the
    /// discriminated union. The `Packet` type must also switch from
    /// `interface extends` to an intersection `type` alias, since TS
    /// interfaces cannot extend a union.
    #[test]
    fn test_zod_row_type_combined_with_outer_join_unions_emits_a_real_union_schema() {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([
                ("row_type".to_string(), "zod".to_string()),
                ("outer_join_unions".to_string(), "true".to_string()),
            ]))
            .unwrap();

        let row_struct = backend
            .generate_row_struct("GetUserOrders", &discriminated_join_columns())
            .unwrap();

        assert!(
            row_struct.contains(".and(z.union(["),
            "must emit a real discriminated union; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("export type GetUserOrdersRowPacket = RowDataPacket & GetUserOrdersRow;"),
            "Packet type must be an intersection, not `interface extends`, since TS \
             interfaces cannot extend a union; got:\n{row_struct}"
        );
    }

    #[test]
    fn test_zod_row_type_without_outer_join_unions_is_unchanged() {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "row_type".to_string(),
                "zod".to_string(),
            )]))
            .unwrap();

        let row_struct = backend
            .generate_row_struct("GetUserOrders", &discriminated_join_columns())
            .unwrap();

        let mut expected = crate::backends::typescript_common::generate_zod_row_struct(
            "GetUserOrdersRow",
            "GetUserOrders",
            &discriminated_join_columns(),
        );
        expected.push_str("\n\nexport interface GetUserOrdersRowPacket extends RowDataPacket, GetUserOrdersRow {}");
        assert_eq!(row_struct, expected);
    }

    fn make_one_query(sql: &str) -> AnalyzedQuery {
        AnalyzedQuery {
            name: "GetUserById".to_string(),
            command: QueryCommand::One,
            sql: sql.to_string(),
            columns: vec![AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            }],
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    fn make_one_query_with_snake_case_column() -> AnalyzedQuery {
        AnalyzedQuery {
            name: "GetSession".to_string(),
            command: QueryCommand::One,
            sql: "SELECT id, user_id FROM sessions WHERE id = ?".to_string(),
            columns: vec![
                AnalyzedColumn {
                    name: "id".to_string(),
                    neutral_type: "int32".to_string(),
                    nullable: false,
                    ..Default::default()
                },
                AnalyzedColumn {
                    name: "user_id".to_string(),
                    neutral_type: "int32".to_string(),
                    nullable: false,
                    ..Default::default()
                },
            ],
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    fn camel_backend() -> TypescriptMysql2Backend {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "field_case".to_string(),
                "camelCase".to_string(),
            )]))
            .unwrap();
        backend
    }

    /// This must fail before the fix: `RowDataPacket`'s `[column: string]:
    /// any` index signature is inherited by anything that `extends` it, so
    /// even a strict camelCase-only interface would still silently accept
    /// `row.user_id` -- masking exactly the bug this backend is supposed to
    /// prevent. Under Camel the declared type must not extend RowDataPacket
    /// at all.
    #[test]
    fn test_row_struct_drops_row_data_packet_base_under_camel_case() {
        let backend = camel_backend();
        let query = make_one_query_with_snake_case_column();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let row_struct = result.row_struct.as_deref().unwrap();

        assert!(
            row_struct.contains("export interface GetSessionRow {"),
            "must be a plain interface with no base; got:\n{row_struct}"
        );
        assert!(
            !row_struct.contains("extends RowDataPacket"),
            "must not extend RowDataPacket under camelCase; got:\n{row_struct}"
        );
    }

    #[test]
    fn test_one_query_fn_remaps_fields_under_camel_case() {
        let backend = camel_backend();
        let query = make_one_query_with_snake_case_column();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("pool.execute<RowDataPacket[]>("),
            "must fetch through bare RowDataPacket, not the struct type; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("userId: row.user_id as number,"),
            "must remap the declared camelCase field from the driver's raw key; got:\n{query_fn}"
        );
    }

    /// This must fail before the fix: mysql2's remap passed `|name, _ty|`
    /// and dropped the type, so every remapped field came back as `any`
    /// through `RowDataPacket`'s `[column: string]: any` index signature.
    /// Every other remap backend casts to the column's declared type, and
    /// without it a wrong type mapping in the manifest is invisible to
    /// `tsc`.
    #[test]
    fn test_remapped_fields_are_cast_to_their_declared_type() {
        let backend = camel_backend();
        let query = make_one_query_with_snake_case_column();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            !query_fn.contains("userId: row.user_id,"),
            "an uncast read leaves the field `any`; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("id: row.id as number,"),
            "every remapped field must carry its cast; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_many_query_fn_remaps_fields_under_camel_case() {
        let backend = camel_backend();
        let mut query = make_one_query_with_snake_case_column();
        query.command = QueryCommand::Many;
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("pool.execute<RowDataPacket[]>("),
            "must fetch through bare RowDataPacket, not the struct type; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("return rows.map((row) => ({"),
            "must map each row; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("userId: row.user_id as number,"),
            "must remap the declared camelCase field from the driver's raw key; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_one_query_fn_keeps_the_typed_generic_under_the_default_snake_case() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_one_query_with_snake_case_column();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("pool.execute<GetSessionRow[]>("),
            "default field_case must keep the original typed generic unchanged; got:\n{query_fn}"
        );
        let row_struct = result.row_struct.as_deref().unwrap();
        assert!(
            row_struct.contains("extends RowDataPacket"),
            "default field_case must keep the RowDataPacket base; got:\n{row_struct}"
        );
    }

    /// Zod mode's bridging `{struct_name}Packet` type exists only to satisfy
    /// mysql2's `execute<T extends RowDataPacket>` constraint for a fetch
    /// that trusts the schema's inferred shape. Under Camel that fetch
    /// always goes through bare `RowDataPacket` instead (see
    /// `generate_row_struct`), so the Packet type has no reason to exist and
    /// must not be generated.
    #[test]
    fn test_zod_row_type_drops_packet_type_under_camel_case() {
        let mut backend = camel_backend();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "row_type".to_string(),
                "zod".to_string(),
            )]))
            .unwrap();
        let query = make_one_query_with_snake_case_column();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let row_struct = result.row_struct.as_deref().unwrap();

        assert!(
            !row_struct.contains("Packet"),
            "camelCase zod mode must not emit a Packet bridging type; got:\n{row_struct}"
        );
    }

    /// MySQL/MariaDB idiomatically backtick-quotes identifiers
    /// (`` `users`.`id` ``). Unescaped, that backtick would terminate the
    /// generated template literal early — this is reachable in real MySQL
    /// SQL, not just adversarial input.
    #[test]
    fn test_query_fn_escapes_user_backtick_in_sql() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_one_query("SELECT `id` FROM `users`");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"SELECT \`id\` FROM \`users\`"),
            "user backticks must be escaped; got:\n{query_fn}"
        );
    }

    /// A literal `${` in the user's SQL must not become a live JS
    /// interpolation.
    #[test]
    fn test_query_fn_escapes_user_dollar_brace_in_sql() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE name = 'literal ${evil}'");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"'literal \${evil}'"),
            "user's literal ${{}} must be escaped; got:\n{query_fn}"
        );
    }

    /// A literal backslash in the user's SQL must be doubled.
    #[test]
    fn test_query_fn_escapes_user_backslash_in_sql() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_one_query(r"SELECT id FROM users WHERE name = 'a\\b'");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"'a\\\\b'"),
            "user backslash must be doubled; got:\n{query_fn}"
        );
    }

    fn make_grouped_query() -> AnalyzedQuery {
        let parent_cols = vec![
            AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            },
            AnalyzedColumn {
                name: "name".to_string(),
                neutral_type: "string".to_string(),
                nullable: false,
                ..Default::default()
            },
        ];
        let child_cols = vec![
            AnalyzedColumn {
                name: "order_id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            },
            AnalyzedColumn {
                name: "total".to_string(),
                neutral_type: "decimal".to_string(),
                nullable: true,
                ..Default::default()
            },
        ];
        let all_cols = [parent_cols.clone(), child_cols.clone()].concat();
        AnalyzedQuery {
            name: "GetUsersWithOrders".to_string(),
            command: QueryCommand::Grouped,
            sql: "SELECT u.id, u.name, o.id AS order_id, o.total FROM users u JOIN orders o ON o.user_id = u.id"
                .to_string(),
            columns: all_cols,
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: Some(GroupByConfig {
                table: "users".to_string(),
                key_column: "id".to_string(),
                parent_columns: parent_cols,
                child_columns: child_cols,
            }),
            custom: vec![],
        }
    }

    #[test]
    fn test_grouped_typescript_mysql2_structs() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let row_struct = result.row_struct.as_deref().unwrap();

        assert!(
            row_struct.contains("interface GetUsersWithOrdersChildRow"),
            "missing child; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("interface GetUsersWithOrdersRow"),
            "missing parent; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("children: GetUsersWithOrdersChildRow[]"),
            "missing children; got:\n{row_struct}"
        );
        let child_pos = row_struct.find("GetUsersWithOrdersChildRow").unwrap();
        let parent_pos = row_struct.find("interface GetUsersWithOrdersRow").unwrap();
        assert!(child_pos < parent_pos, "child must precede parent");
    }

    #[test]
    fn test_grouped_typescript_mysql2_query_fn() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(query_fn.contains("getUsersWithOrders"), "missing fn; got:\n{query_fn}");
        assert!(
            query_fn.contains("Promise<GetUsersWithOrdersRow[]>"),
            "wrong return type; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("pool.execute<RowDataPacket[]>"),
            "must use pool.execute; got:\n{query_fn}"
        );
        assert!(query_fn.contains("row.id"), "must use dot access; got:\n{query_fn}");
        assert!(
            query_fn.contains("new Map<unknown, GetUsersWithOrdersRow>()"),
            "must use Map; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("parent.children.push"),
            "must fold children; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_structs_only_suppresses_query_fn_and_drops_pool_but_keeps_row_data_packet() {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "structs_only".to_string(),
                "true".to_string(),
            )]))
            .unwrap();

        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert_eq!(
            result.query_fn.as_deref(),
            Some(""),
            "structs_only must suppress the query function"
        );
        assert!(
            result
                .row_struct
                .as_deref()
                .unwrap()
                .contains("interface GetUserByIdRow extends RowDataPacket"),
            "row struct must still be emitted"
        );

        let header = backend.file_header();
        assert!(
            !header.contains("Pool"),
            "the unused Pool driver import must be dropped; got:\n{header}"
        );
        assert!(
            header.contains("RowDataPacket"),
            "RowDataPacket stays imported since the row type still extends it; got:\n{header}"
        );
    }

    #[test]
    fn test_structs_only_unset_leaves_query_fn_present() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert!(
            !result.query_fn.as_deref().unwrap().is_empty(),
            "without structs_only the query function must still be generated"
        );
        assert!(backend.file_header().contains("Pool, RowDataPacket"));
    }

    #[test]
    fn test_structs_only_rejects_invalid_value() {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let result = backend.apply_options(&std::collections::HashMap::from([(
            "structs_only".to_string(),
            "maybe".to_string(),
        )]));
        assert!(result.is_err(), "expected 'maybe' to be rejected");
    }

    #[test]
    fn test_structs_only_combined_with_zod_row_type_keeps_zod_import_and_schema() {
        let mut backend = TypescriptMysql2Backend::new("mysql").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([
                ("structs_only".to_string(), "true".to_string()),
                ("row_type".to_string(), "zod".to_string()),
            ]))
            .unwrap();

        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert_eq!(result.query_fn.as_deref(), Some(""));
        assert!(
            result.row_struct.as_deref().unwrap().contains("z.object({"),
            "zod schema must still be emitted"
        );

        let header = backend.file_header();
        assert!(header.contains("import { z } from \"zod\";"), "got:\n{header}");
        assert!(!header.contains("Pool"), "got:\n{header}");
    }

    /// This must fail before the fix: the header hardcoded `RowDataPacket`
    /// on the justification that every generated row type extends or
    /// intersects it. Under Camel they no longer do, and `structs_only`
    /// removes the query functions that hold the only other reference — so
    /// the import was emitted with nothing referencing it, which
    /// `noUnusedLocals` rejects.
    #[test]
    fn test_camel_case_with_structs_only_emits_no_driver_import() {
        let mut backend = camel_backend();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "structs_only".to_string(),
                "true".to_string(),
            )]))
            .unwrap();

        assert_eq!(backend.file_header(), "/** Auto-generated by scythe. Do not edit. */\n");
    }

    /// The zod import is independent of the driver import, so it must
    /// survive on its own when the driver import drops out.
    #[test]
    fn test_camel_case_with_structs_only_keeps_the_zod_import_alone() {
        let mut backend = camel_backend();
        backend
            .apply_options(&std::collections::HashMap::from([
                ("structs_only".to_string(), "true".to_string()),
                ("row_type".to_string(), "zod".to_string()),
            ]))
            .unwrap();

        assert_eq!(
            backend.file_header(),
            "/** Auto-generated by scythe. Do not edit. */\n\nimport { z } from \"zod\";\n"
        );
    }

    /// Without `structs_only` the query functions still fetch through
    /// `pool.execute<RowDataPacket[]>`, so the import is genuinely
    /// referenced even though the row types dropped the base.
    #[test]
    fn test_camel_case_keeps_row_data_packet_when_query_fns_are_generated() {
        let backend = camel_backend();
        assert_eq!(
            backend.file_header(),
            "/** Auto-generated by scythe. Do not edit. */\n\n\
             import type { Pool, RowDataPacket } from \"mysql2/promise\";\n"
        );
    }

    fn make_batch_query(name: &str, sql: &str, params: Vec<AnalyzedParam>) -> AnalyzedQuery {
        AnalyzedQuery {
            name: name.to_string(),
            command: QueryCommand::Batch,
            sql: sql.to_string(),
            columns: vec![],
            params,
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    /// Regression test: `write_fn_sig`'s wrapped (>80 char) branch used to
    /// discard the `params_inline`/`sig_params` it was given and rebuild the
    /// signature from the outer per-column `params` slice instead. For a
    /// `:batch` function that slice is wrong -- the actual signature takes
    /// `items: XBatchParams[]`, not the raw columns -- so the emitted
    /// function declared parameters that didn't match its body (which
    /// references `items`). This must fail if that fallback is reinstated.
    #[test]
    fn test_batch_signature_wrap_declares_items_not_raw_columns() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_batch_query(
            "CreateUserAccountRecord",
            "INSERT INTO user_account_record (name, email) VALUES (?, ?)",
            vec![
                AnalyzedParam {
                    name: "name".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 1,
                },
                AnalyzedParam {
                    name: "email".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 2,
                },
            ],
        );

        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("\titems: CreateUserAccountRecordRowBatchParams[],"),
            "wrapped batch signature must declare items with the batch params type; got:\n{query_fn}"
        );
        assert!(
            !query_fn.contains("\tname: string,") && !query_fn.contains("\temail: string,"),
            "wrapped batch signature must not fall back to the raw per-column params; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("for (const item of items)"),
            "every identifier the body references (items) must be declared in the signature; got:\n{query_fn}"
        );
    }

    /// Regression test guarding against a naive fix that splits
    /// `params_inline` on top-level `", "` to recover individual parameters.
    /// A `json` param's TS type is `Record<string, unknown>`, which itself
    /// contains `", "` -- splitting on it would corrupt a single parameter
    /// into `payload: Record<string` and `unknown>[]`. The structured
    /// `(name, type)` pairs must survive a wrapped signature intact.
    #[test]
    fn test_batch_signature_wrap_preserves_json_param_type_intact() {
        let backend = TypescriptMysql2Backend::new("mysql").unwrap();
        let query = make_batch_query(
            "CreateUserAccountRecordPayload",
            "INSERT INTO user_account_record_payload (payload) VALUES (?)",
            vec![AnalyzedParam {
                name: "payload".to_string(),
                neutral_type: "json".to_string(),
                nullable: false,
                position: 1,
            }],
        );

        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("\titems: Record<string, unknown>[],"),
            "the json param's type must survive intact on the items line, not be split \
             on its internal ', '; got:\n{query_fn}"
        );
        assert!(
            !query_fn.contains("Record<string,\n"),
            "the json type must not be split at its internal comma; got:\n{query_fn}"
        );
    }
}
