use scythe_backend::manifest::BackendManifest;
use scythe_backend::naming::{enum_type_name, fn_name, row_struct_name, to_camel_case, to_pascal_case};
use scythe_backend::types::resolve_type;
use std::fmt::Write;

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::GroupedQueryFn;
use crate::backend_trait::{CodegenBackend, ResolvedColumn, ResolvedParam};
use crate::backends::typescript_common::{
    TsRowType, escape_ts_template_literal, generate_grouped_interface_structs, generate_ts_grouped_fold_body,
    generate_ts_interface_row_struct, generate_ts_union_row_struct, generate_zod_grouped_structs,
    generate_zod_row_struct, generate_zod_union_row_struct, parse_bool_option,
};
use crate::singularize;

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/typescript-wasm-sqlite.toml");

/// Codegen backend for `@sqlite.org/sqlite-wasm`'s synchronous OO1 API.
///
/// Unlike `better-sqlite3`, the WASM build runs in-process (browser or Node)
/// behind a one-time async `sqlite3InitModule()` that user code performs
/// before ever calling into generated functions. The `Database` handle these
/// functions receive is already open, and every OO1 method used here
/// (`selectObject`, `selectObjects`, `exec`, `changes`, `transaction`) is
/// fully synchronous — no `async`/`await`/`Promise` appears anywhere in the
/// generated output. See <https://github.com/sqlite/sqlite-wasm>.
pub struct TypescriptWasmSqliteBackend {
    manifest: BackendManifest,
    row_type: TsRowType,
    /// Emit outer-join nullability as a discriminated union instead of
    /// independent per-column optionals. Opt-in: the flat shape stays the
    /// default and the cross-target shape.
    outer_join_unions: bool,
    /// When true, only emit type definitions (interfaces/Zod schemas, enums,
    /// composites) — no query functions, and no `@sqlite.org/sqlite-wasm`
    /// driver import (which would otherwise be unused).
    structs_only: bool,
}

impl TypescriptWasmSqliteBackend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "sqlite" | "sqlite3" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!("typescript-wasm-sqlite only supports SQLite, got engine '{}'", engine),
                ));
            }
        }
        let manifest =
            super::load_or_default_manifest("backends/typescript-wasm-sqlite/manifest.toml", DEFAULT_MANIFEST_TOML)?;
        Ok(Self {
            manifest,
            row_type: TsRowType::default(),
            outer_join_unions: false,
            structs_only: false,
        })
    }
}

impl CodegenBackend for TypescriptWasmSqliteBackend {
    fn name(&self) -> &str {
        "typescript-wasm-sqlite"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["sqlite"]
    }

    fn file_header(&self) -> String {
        if self.structs_only {
            let mut header = "/** Auto-generated by scythe. Do not edit. */\n".to_string();
            if self.row_type == TsRowType::Zod {
                header.push_str("\nimport { z } from \"zod\";\n");
            }
            return header;
        }
        let mut header = "/** Auto-generated by scythe. Do not edit. */\n\n\
            import type { Database } from \"@sqlite.org/sqlite-wasm\";\n"
            .to_string();
        if self.row_type == TsRowType::Zod {
            header.push_str("import { z } from \"zod\";\n");
        }
        header
    }

    fn generate_row_struct(&self, query_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        if self.row_type == TsRowType::Zod {
            if self.outer_join_unions {
                return Ok(generate_zod_union_row_struct(&struct_name, query_name, columns));
            }
            return Ok(generate_zod_row_struct(&struct_name, query_name, columns));
        }
        if self.outer_join_unions {
            return Ok(generate_ts_union_row_struct(&struct_name, query_name, columns, None));
        }
        Ok(generate_ts_interface_row_struct(&struct_name, query_name, columns))
    }

    fn generate_model_struct(&self, table_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let singular = singularize(table_name);
        let name = to_pascal_case(&singular);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        _columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        if self.structs_only {
            return Ok(String::new());
        }

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let mut out = String::new();

        let sql = escape_ts_template_literal(&super::clean_sql_with_optional(
            &analyzed.sql,
            &analyzed.optional_params,
            &analyzed.params,
        ));

        // Takes structured `(name, type)` pairs rather than a pre-joined
        // string. A naive split of a pre-joined `params_inline` on `", "`
        // would corrupt a `json` param's TS type (`Record<string, unknown>`,
        // which itself contains `", "`) into two broken parameters; deriving
        // both the one-liner and the wrapped form from the same slice avoids
        // that entirely and also keeps this closure honest about wrapping
        // whatever it was actually given -- rather than re-deriving
        // parameters from the enclosing `params` slice, which silently
        // produces the wrong signature whenever the signature isn't the
        // plain per-query parameter list (e.g. the `items: XBatchParams[]` /
        // `count: number` forms used for `:batch` queries).
        let write_fn_sig = |out: &mut String, name: &str, sig_params: &[(String, String)], ret: &str| {
            let params_inline = sig_params
                .iter()
                .map(|(n, t)| format!("{n}: {t}"))
                .collect::<Vec<_>>()
                .join(", ");
            let oneliner = format!("export function {}({}): {} {{", name, params_inline, ret);
            if oneliner.len() <= 80 {
                let _ = writeln!(out, "{}", oneliner);
            } else {
                let _ = writeln!(out, "export function {}(", name);
                for (n, t) in sig_params {
                    let _ = writeln!(out, "\t{}: {},", n, t);
                }
                let _ = writeln!(out, "): {} {{", ret);
            }
        };

        let query_sig_params: Vec<(String, String)> = std::iter::once(("db".to_string(), "Database".to_string()))
            .chain(params.iter().map(|p| (p.field_name.clone(), p.full_type.clone())))
            .collect();

        let bind_array = if params.is_empty() {
            String::new()
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            format!("[{}]", args.join(", "))
        };

        match &analyzed.command {
            QueryCommand::One | QueryCommand::Opt => {
                let _ = writeln!(out, "/** Fetch a single {} or null. */", struct_name);
                let ret = format!("{} | null", struct_name);
                write_fn_sig(&mut out, &func_name, &query_sig_params, &ret);
                if params.is_empty() {
                    let _ = writeln!(
                        out,
                        "\tconst row = db.selectObject(`{}`) as unknown as {} | undefined;",
                        sql, struct_name
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "\tconst row = db.selectObject(`{}`, {}) as unknown as {} | undefined;",
                        sql, bind_array, struct_name
                    );
                }
                let _ = writeln!(out, "\treturn row ?? null;");
                let _ = write!(out, "}}");
            }
            QueryCommand::Batch => {
                let batch_fn_name = format!("{}Batch", func_name);
                if params.len() > 1 {
                    let params_type_name = format!("{}BatchParams", struct_name);
                    let _ = writeln!(out, "/** Params for {} batch operation. */", struct_name);
                    let _ = writeln!(out, "export interface {} {{", params_type_name);
                    for p in params {
                        let _ = writeln!(out, "\t{}: {};", p.field_name, p.full_type);
                    }
                    let _ = writeln!(out, "}}");
                    let _ = writeln!(out);
                    let _ = writeln!(
                        out,
                        "/** Execute {} for each item in the batch within a transaction. */",
                        analyzed.name
                    );
                    let batch_sig_params = vec![
                        ("db".to_string(), "Database".to_string()),
                        ("items".to_string(), format!("{}[]", params_type_name)),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "void");
                    let _ = writeln!(out, "\tdb.transaction(() => {{");
                    let _ = writeln!(out, "\t\tfor (const item of items) {{");
                    let args: Vec<String> = params.iter().map(|p| format!("item.{}", p.field_name)).collect();
                    let _ = writeln!(out, "\t\t\tdb.exec({{ sql: `{}`, bind: [{}] }});", sql, args.join(", "));
                    let _ = writeln!(out, "\t\t}}");
                    let _ = writeln!(out, "\t}});");
                    let _ = write!(out, "}}");
                } else if params.len() == 1 {
                    let _ = writeln!(
                        out,
                        "/** Execute {} for each item in the batch within a transaction. */",
                        analyzed.name
                    );
                    let batch_sig_params = vec![
                        ("db".to_string(), "Database".to_string()),
                        ("items".to_string(), format!("{}[]", params[0].full_type)),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "void");
                    let _ = writeln!(out, "\tdb.transaction(() => {{");
                    let _ = writeln!(out, "\t\tfor (const item of items) {{");
                    let _ = writeln!(out, "\t\t\tdb.exec({{ sql: `{}`, bind: [item] }});", sql);
                    let _ = writeln!(out, "\t\t}}");
                    let _ = writeln!(out, "\t}});");
                    let _ = write!(out, "}}");
                } else {
                    let _ = writeln!(
                        out,
                        "/** Execute {} for each item in the batch within a transaction. */",
                        analyzed.name
                    );
                    let batch_sig_params = vec![
                        ("db".to_string(), "Database".to_string()),
                        ("count".to_string(), "number".to_string()),
                    ];
                    write_fn_sig(&mut out, &batch_fn_name, &batch_sig_params, "void");
                    let _ = writeln!(out, "\tdb.transaction(() => {{");
                    let _ = writeln!(out, "\t\tfor (let i = 0; i < count; i++) db.exec(`{}`);", sql);
                    let _ = writeln!(out, "\t}});");
                    let _ = write!(out, "}}");
                }
            }
            QueryCommand::Many => {
                let _ = writeln!(out, "/** Fetch all {} rows. */", struct_name);
                let ret = format!("{}[]", struct_name);
                write_fn_sig(&mut out, &func_name, &query_sig_params, &ret);
                if params.is_empty() {
                    let _ = writeln!(
                        out,
                        "\treturn db.selectObjects(`{}`) as unknown as {}[];",
                        sql, struct_name
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "\treturn db.selectObjects(`{}`, {}) as unknown as {}[];",
                        sql, bind_array, struct_name
                    );
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::Exec => {
                let _ = writeln!(out, "/** Execute a query returning no rows. */");
                write_fn_sig(&mut out, &func_name, &query_sig_params, "void");
                if params.is_empty() {
                    let _ = writeln!(out, "\tdb.exec(`{}`);", sql);
                } else {
                    let _ = writeln!(out, "\tdb.exec({{ sql: `{}`, bind: {} }});", sql, bind_array);
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                let _ = writeln!(out, "/** Execute a query and return the number of affected rows. */");
                write_fn_sig(&mut out, &func_name, &query_sig_params, "number");
                if params.is_empty() {
                    let _ = writeln!(out, "\tdb.exec(`{}`);", sql);
                } else {
                    let _ = writeln!(out, "\tdb.exec({{ sql: `{}`, bind: {} }});", sql, bind_array);
                }
                let _ = writeln!(out, "\treturn db.changes();");
                let _ = write!(out, "}}");
            }
            QueryCommand::Grouped => {
                unreachable!("Grouped command is routed through generate_grouped_query_fn, not generate_query_fn")
            }
        }

        Ok(out)
    }

    fn generate_grouped_structs(
        &self,
        parent_struct_name: &str,
        child_struct_name: &str,
        parent_columns: &[ResolvedColumn],
        child_columns: &[ResolvedColumn],
        _key_column: &str,
    ) -> Result<String, ScytheError> {
        if self.row_type == TsRowType::Zod {
            return Ok(generate_zod_grouped_structs(
                child_struct_name,
                parent_struct_name,
                parent_columns,
                child_columns,
            ));
        }
        Ok(generate_grouped_interface_structs(
            child_struct_name,
            parent_struct_name,
            parent_columns,
            child_columns,
        ))
    }

    fn generate_grouped_query_fn(&self, request: &GroupedQueryFn<'_>) -> Result<String, ScytheError> {
        let analyzed = request.analyzed;
        let parent_struct_name = request.parent_struct_name;
        let child_struct_name = request.child_struct_name;
        let parent_columns = request.parent_columns;
        let child_columns = request.child_columns;
        let params = request.params;
        let key_column = request.key_column;

        if self.structs_only {
            return Ok(String::new());
        }

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = escape_ts_template_literal(&super::clean_sql_with_optional(
            &analyzed.sql,
            &analyzed.optional_params,
            &analyzed.params,
        ));

        let param_list = params
            .iter()
            .map(|p| format!("{}: {}", p.field_name, p.full_type))
            .collect::<Vec<_>>()
            .join(", ");
        let inline_params = if params.is_empty() {
            "db: Database".to_string()
        } else {
            format!("db: Database, {}", param_list)
        };
        let ret = format!("{parent_struct_name}[]");

        let mut out = String::new();
        let oneliner = format!("export function {func_name}({inline_params}): {ret} {{");
        if oneliner.len() <= 80 {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "{oneliner}");
        } else {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "export function {func_name}(");
            let _ = writeln!(out, "\tdb: Database,");
            for p in params {
                let _ = writeln!(out, "\t{}: {},", p.field_name, p.full_type);
            }
            let _ = writeln!(out, "): {ret} {{");
        }

        if params.is_empty() {
            let _ = writeln!(
                out,
                "\tconst flatRows = db.selectObjects(`{sql}`) as Record<string, unknown>[];"
            );
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            let _ = writeln!(
                out,
                "\tconst flatRows = db.selectObjects(`{sql}`, [{}]) as Record<string, unknown>[];",
                args.join(", ")
            );
        }

        let fold = generate_ts_grouped_fold_body(
            parent_struct_name,
            child_struct_name,
            parent_columns,
            child_columns,
            key_column,
            |name, ty| format!("row['{name}'] as {ty}"),
        );
        out.push_str(&fold);
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        let type_name = enum_type_name(&enum_info.sql_name, &self.manifest.naming);
        if self.row_type == TsRowType::Zod {
            return Ok(super::typescript_common::generate_zod_enum(
                &type_name,
                &enum_info.values,
            ));
        }
        let mut out = String::new();
        let variants: Vec<String> = enum_info.values.iter().map(|v| format!("\"{}\"", v)).collect();
        let _ = write!(out, "export type {} = {};", type_name, variants.join(" | "));
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        let _ = writeln!(out, "/** Composite type {}. */", composite.sql_name);
        let _ = writeln!(out, "export interface {} {{", name);
        for field in &composite.fields {
            let ts_type = resolve_type(&field.neutral_type, &self.manifest, false)
                .map(|t| t.into_owned())
                .map_err(|e| {
                    ScytheError::new(ErrorCode::InternalError, format!("composite field type error: {}", e))
                })?;
            let _ = writeln!(out, "\t{}: {};", to_camel_case(&field.name), ts_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn apply_options(&mut self, options: &std::collections::HashMap<String, String>) -> Result<(), ScytheError> {
        if let Some(value) = options.get("row_type") {
            self.row_type = TsRowType::from_option(value)?;
        }
        if let Some(value) = options.get("outer_join_unions") {
            self.outer_join_unions = parse_bool_option("outer_join_unions", value)?;
        }
        if let Some(value) = options.get("structs_only") {
            self.structs_only = parse_bool_option("structs_only", value)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::TypescriptWasmSqliteBackend;
    use crate::backend_trait::CodegenBackend;
    use scythe_core::analyzer::{AnalyzedColumn, AnalyzedParam, AnalyzedQuery, GroupByConfig};
    use scythe_core::parser::QueryCommand;

    fn discriminated_join_columns() -> Vec<crate::backend_trait::ResolvedColumn> {
        use crate::backend_trait::ResolvedColumn;
        vec![
            ResolvedColumn {
                name: "id".to_string(),
                field_name: "id".to_string(),
                lang_type: "number".to_string(),
                full_type: "number".to_string(),
                neutral_type: "int32".to_string(),
                sql_type: "int4".to_string(),
                nullable: false,
                join_group: None,
                nullable_before_join: false,
            },
            ResolvedColumn {
                name: "total".to_string(),
                field_name: "total".to_string(),
                lang_type: "string".to_string(),
                full_type: "string | null".to_string(),
                neutral_type: "decimal".to_string(),
                sql_type: "numeric".to_string(),
                nullable: true,
                join_group: Some("o".to_string()),
                nullable_before_join: false,
            },
        ]
    }

    #[test]
    fn test_engine_rejection_for_non_sqlite() {
        let result = TypescriptWasmSqliteBackend::new("postgresql");
        assert!(result.is_err(), "typescript-wasm-sqlite must reject non-sqlite engines");
    }

    #[test]
    fn test_engine_acceptance_for_sqlite_aliases() {
        assert!(TypescriptWasmSqliteBackend::new("sqlite").is_ok());
        assert!(TypescriptWasmSqliteBackend::new("sqlite3").is_ok());
    }

    #[test]
    fn test_file_header_imports_database_type_from_sqlite_wasm() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let header = backend.file_header();
        assert!(
            header.contains("import type { Database } from \"@sqlite.org/sqlite-wasm\";"),
            "must import the Database type from @sqlite.org/sqlite-wasm; got:\n{header}"
        );
        assert!(!header.contains("zod"), "zod import must be opt-in; got:\n{header}");
    }

    #[test]
    fn test_zod_row_type_combined_with_outer_join_unions_emits_a_real_union_schema() {
        let mut backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([
                ("row_type".to_string(), "zod".to_string()),
                ("outer_join_unions".to_string(), "true".to_string()),
            ]))
            .unwrap();

        let row_struct = backend
            .generate_row_struct("GetUserOrders", &discriminated_join_columns())
            .unwrap();

        assert!(
            row_struct.contains(".and(z.union(["),
            "must emit a real discriminated union; got:\n{row_struct}"
        );
    }

    #[test]
    fn test_zod_row_type_without_outer_join_unions_is_unchanged() {
        let mut backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "row_type".to_string(),
                "zod".to_string(),
            )]))
            .unwrap();

        let row_struct = backend
            .generate_row_struct("GetUserOrders", &discriminated_join_columns())
            .unwrap();

        assert_eq!(
            row_struct,
            crate::backends::typescript_common::generate_zod_row_struct(
                "GetUserOrdersRow",
                "GetUserOrders",
                &discriminated_join_columns()
            )
        );
    }

    fn make_one_query(sql: &str) -> AnalyzedQuery {
        AnalyzedQuery {
            name: "GetUserById".to_string(),
            command: QueryCommand::One,
            sql: sql.to_string(),
            columns: vec![AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            }],
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    #[test]
    fn test_query_fn_escapes_user_backtick_in_sql() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE name = `oops`");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"WHERE name = \`oops\`"),
            "user backtick must be escaped; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_query_fn_escapes_user_dollar_brace_in_sql() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE name = 'literal ${evil}'");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"'literal \${evil}'"),
            "user's literal ${{}} must be escaped; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_query_fn_escapes_user_backslash_in_sql() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_one_query(r"SELECT id FROM users WHERE name = 'a\\b'");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains(r"'a\\\\b'"),
            "user backslash must be doubled; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_one_query_fn_is_synchronous_and_uses_select_object() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("db.selectObject(`"),
            "must use selectObject; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("as unknown as GetUserByIdRow | undefined"),
            "must cast through unknown; got:\n{query_fn}"
        );
    }

    fn make_many_query() -> AnalyzedQuery {
        AnalyzedQuery {
            name: "ListUsers".to_string(),
            command: QueryCommand::Many,
            sql: "SELECT id FROM users".to_string(),
            columns: vec![AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            }],
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    #[test]
    fn test_many_query_fn_is_synchronous_and_uses_select_objects() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_many_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("db.selectObjects(`"),
            "must use selectObjects; got:\n{query_fn}"
        );
    }

    fn make_exec_query() -> AnalyzedQuery {
        AnalyzedQuery {
            name: "DeleteUser".to_string(),
            command: QueryCommand::Exec,
            sql: "DELETE FROM users WHERE id = ?".to_string(),
            columns: vec![],
            params: vec![scythe_core::analyzer::AnalyzedParam {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                position: 1,
            }],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    #[test]
    fn test_exec_query_fn_is_synchronous_and_uses_exec() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_exec_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("db.exec({ sql: `"),
            "must use db.exec with bind; got:\n{query_fn}"
        );
        assert!(query_fn.contains(": void"), "Exec returns void; got:\n{query_fn}");
    }

    fn make_exec_result_query() -> AnalyzedQuery {
        AnalyzedQuery {
            name: "UpdateUserName".to_string(),
            command: QueryCommand::ExecResult,
            sql: "UPDATE users SET name = ? WHERE id = ?".to_string(),
            columns: vec![],
            params: vec![
                scythe_core::analyzer::AnalyzedParam {
                    name: "name".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 1,
                },
                scythe_core::analyzer::AnalyzedParam {
                    name: "id".to_string(),
                    neutral_type: "int32".to_string(),
                    nullable: false,
                    position: 2,
                },
            ],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    #[test]
    fn test_exec_result_query_fn_is_synchronous_and_returns_changes() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_exec_result_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("return db.changes();"),
            "must return db.changes(); got:\n{query_fn}"
        );
        assert!(
            query_fn.contains(": number"),
            "ExecResult returns number; got:\n{query_fn}"
        );
    }

    fn make_batch_query() -> AnalyzedQuery {
        AnalyzedQuery {
            name: "InsertUser".to_string(),
            command: QueryCommand::Batch,
            sql: "INSERT INTO users (id, name) VALUES (?, ?)".to_string(),
            columns: vec![],
            params: vec![
                scythe_core::analyzer::AnalyzedParam {
                    name: "id".to_string(),
                    neutral_type: "int32".to_string(),
                    nullable: false,
                    position: 1,
                },
                scythe_core::analyzer::AnalyzedParam {
                    name: "name".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 2,
                },
            ],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    #[test]
    fn test_batch_query_fn_is_synchronous_and_uses_db_transaction() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_batch_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("db.transaction(() => {"),
            "must use db.transaction; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("export interface InsertUserRowBatchParams"),
            "multi-param batch needs a params interface; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("export function insertUserBatch"),
            "missing batch fn; got:\n{query_fn}"
        );
        // Regression coverage: a wrapped (>80 char) signature must render the
        // `items: XBatchParams[]` parameter it was actually given, not fall back to
        // the query's own per-column parameter list.
        assert!(
            query_fn.contains("\titems: InsertUserRowBatchParams[],"),
            "wrapped signature must use the items array param; got:\n{query_fn}"
        );
        assert!(
            !query_fn.contains("\tid: number,\n\tname: string,"),
            "wrapped signature must not fall back to per-column params; got:\n{query_fn}"
        );
    }

    fn make_grouped_query() -> AnalyzedQuery {
        let parent_cols = vec![
            AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            },
            AnalyzedColumn {
                name: "name".to_string(),
                neutral_type: "string".to_string(),
                nullable: false,
                ..Default::default()
            },
        ];
        let child_cols = vec![
            AnalyzedColumn {
                name: "order_id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
                ..Default::default()
            },
            AnalyzedColumn {
                name: "total".to_string(),
                neutral_type: "decimal".to_string(),
                nullable: true,
                ..Default::default()
            },
        ];
        let all_cols = [parent_cols.clone(), child_cols.clone()].concat();
        AnalyzedQuery {
            name: "GetUsersWithOrders".to_string(),
            command: QueryCommand::Grouped,
            sql: "SELECT u.id, u.name, o.id AS order_id, o.total FROM users u JOIN orders o ON o.user_id = u.id"
                .to_string(),
            columns: all_cols,
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: Some(GroupByConfig {
                table: "users".to_string(),
                key_column: "id".to_string(),
                parent_columns: parent_cols,
                child_columns: child_cols,
            }),
            custom: vec![],
        }
    }

    #[test]
    fn test_grouped_typescript_wasm_sqlite_structs() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let row_struct = result.row_struct.as_deref().unwrap();

        assert!(
            row_struct.contains("interface GetUsersWithOrdersChildRow"),
            "missing child; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("interface GetUsersWithOrdersRow"),
            "missing parent; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("children: GetUsersWithOrdersChildRow[]"),
            "missing children; got:\n{row_struct}"
        );
        let child_pos = row_struct.find("GetUsersWithOrdersChildRow").unwrap();
        let parent_pos = row_struct.find("interface GetUsersWithOrdersRow").unwrap();
        assert!(child_pos < parent_pos, "child must precede parent");
    }

    #[test]
    fn test_grouped_typescript_wasm_sqlite_query_fn() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(!query_fn.contains("async function"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("await"), "must be sync; got:\n{query_fn}");
        assert!(!query_fn.contains("Promise"), "must be sync; got:\n{query_fn}");
        assert!(
            query_fn.contains("export function getUsersWithOrders"),
            "missing fn; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("GetUsersWithOrdersRow[]"),
            "wrong return type; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("db.selectObjects(`"),
            "must call db.selectObjects; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("new Map<unknown, GetUsersWithOrdersRow>()"),
            "must use Map; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("parent.children.push"),
            "must fold children; got:\n{query_fn}"
        );
    }

    fn make_named_batch_query(name: &str, sql: &str, params: Vec<AnalyzedParam>) -> AnalyzedQuery {
        AnalyzedQuery {
            name: name.to_string(),
            command: QueryCommand::Batch,
            sql: sql.to_string(),
            columns: vec![],
            params,
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: None,
            custom: vec![],
        }
    }

    /// Regression test: `write_fn_sig`'s wrapped (>80 char) branch used to
    /// discard the `params_inline`/`sig_params` it was given and rebuild the
    /// signature from the outer per-column `params` slice instead. For a
    /// `:batch` function that slice is wrong -- the actual signature takes
    /// `items: XBatchParams[]`, not the raw columns -- so the emitted
    /// function declared parameters that didn't match its body (which
    /// references `items`). This must fail if that fallback is reinstated.
    #[test]
    fn test_batch_signature_wrap_declares_items_not_raw_columns() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_named_batch_query(
            "CreateUserAccountRecord",
            "INSERT INTO user_account_record (name, email) VALUES (?, ?)",
            vec![
                AnalyzedParam {
                    name: "name".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 1,
                },
                AnalyzedParam {
                    name: "email".to_string(),
                    neutral_type: "string".to_string(),
                    nullable: false,
                    position: 2,
                },
            ],
        );

        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("\titems: CreateUserAccountRecordRowBatchParams[],"),
            "wrapped batch signature must declare items with the batch params type; got:\n{query_fn}"
        );
        assert!(
            !query_fn.contains("\tname: string,") && !query_fn.contains("\temail: string,"),
            "wrapped batch signature must not fall back to the raw per-column params; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("db.transaction(() => {"),
            "every identifier the body references (items) must be declared in the signature; got:\n{query_fn}"
        );
    }

    /// The critical regression test for this backend specifically: it used
    /// to split a pre-joined `params_inline` string on top-level `", "` to
    /// recover individual parameters for the wrapped form. A `json` param's
    /// TS type is `Record<string, unknown>`, which itself contains `", "` --
    /// splitting on it corrupted a single parameter into
    /// `payload: Record<string` and `unknown>[]`. The structured
    /// `(name, type)` pairs must survive a wrapped signature intact.
    #[test]
    fn test_batch_signature_wrap_preserves_json_param_type_intact() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_named_batch_query(
            "CreateUserAccountRecordPayload",
            "INSERT INTO user_account_record_payload (payload) VALUES (?)",
            vec![AnalyzedParam {
                name: "payload".to_string(),
                neutral_type: "json".to_string(),
                nullable: false,
                position: 1,
            }],
        );

        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(
            query_fn.contains("\titems: Record<string, unknown>[],"),
            "the json param's type must survive intact on the items line, not be split \
             on its internal ', '; got:\n{query_fn}"
        );
        assert!(
            !query_fn.contains("Record<string,\n"),
            "the json type must not be split at its internal comma; got:\n{query_fn}"
        );
    }

    #[test]
    fn test_structs_only_suppresses_query_fn_and_driver_import() {
        let mut backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([(
                "structs_only".to_string(),
                "true".to_string(),
            )]))
            .unwrap();

        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert_eq!(
            result.query_fn.as_deref(),
            Some(""),
            "structs_only must suppress the query function"
        );
        assert!(
            result
                .row_struct
                .as_deref()
                .unwrap()
                .contains("interface GetUserByIdRow"),
            "row struct must still be emitted"
        );

        let header = backend.file_header();
        assert!(
            !header.contains("@sqlite.org/sqlite-wasm"),
            "the unused sqlite-wasm driver import must be dropped; got:\n{header}"
        );
    }

    #[test]
    fn test_structs_only_unset_leaves_query_fn_present() {
        let backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert!(
            !result.query_fn.as_deref().unwrap().is_empty(),
            "without structs_only the query function must still be generated"
        );
        assert!(
            backend
                .file_header()
                .contains("import type { Database } from \"@sqlite.org/sqlite-wasm\";")
        );
    }

    #[test]
    fn test_structs_only_rejects_invalid_value() {
        let mut backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        let result = backend.apply_options(&std::collections::HashMap::from([(
            "structs_only".to_string(),
            "maybe".to_string(),
        )]));
        assert!(result.is_err(), "expected 'maybe' to be rejected");
    }

    #[test]
    fn test_structs_only_combined_with_zod_row_type_keeps_zod_import_and_schema() {
        let mut backend = TypescriptWasmSqliteBackend::new("sqlite").unwrap();
        backend
            .apply_options(&std::collections::HashMap::from([
                ("structs_only".to_string(), "true".to_string()),
                ("row_type".to_string(), "zod".to_string()),
            ]))
            .unwrap();

        let query = make_one_query("SELECT id FROM users WHERE id = ?");
        let result = crate::generate_with_backend(&query, &backend).unwrap();

        assert_eq!(result.query_fn.as_deref(), Some(""));
        assert!(
            result.row_struct.as_deref().unwrap().contains("z.object({"),
            "zod schema must still be emitted"
        );

        let header = backend.file_header();
        assert!(header.contains("import { z } from \"zod\";"), "got:\n{header}");
        assert!(!header.contains("@sqlite.org/sqlite-wasm"), "got:\n{header}");
    }
}
