use scythe_backend::manifest::BackendManifest;
use scythe_backend::naming::{enum_type_name, fn_name, row_struct_name, to_camel_case, to_pascal_case};
use scythe_backend::types::resolve_type;
use std::collections::HashMap;
use std::fmt::Write;

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::{CodegenBackend, GroupedQueryFn, ResolvedColumn, ResolvedParam};
use crate::backends::typescript_common::{
    TsRowType, generate_grouped_interface_structs, generate_ts_grouped_fold_body,
};
use crate::singularize;

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/typescript-oracledb.toml");

pub struct TypescriptOracledbBackend {
    manifest: BackendManifest,
    row_type: TsRowType,
}

impl TypescriptOracledbBackend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "oracle" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!("typescript-oracledb only supports Oracle, got engine '{}'", engine),
                ));
            }
        }
        let manifest =
            super::load_or_default_manifest("backends/typescript-oracledb/manifest.toml", DEFAULT_MANIFEST_TOML)?;
        Ok(Self {
            manifest,
            row_type: TsRowType::default(),
        })
    }
}

/// Rewrite $1, $2, ... positional params to :1, :2, ... for Oracle.
impl CodegenBackend for TypescriptOracledbBackend {
    fn name(&self) -> &str {
        "typescript-oracledb"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["oracle"]
    }

    fn apply_options(&mut self, options: &HashMap<String, String>) -> Result<(), ScytheError> {
        if let Some(rt) = options.get("row_type") {
            self.row_type = TsRowType::from_option(rt)?;
        }
        Ok(())
    }

    fn file_header(&self) -> String {
        "// Auto-generated by scythe. Do not edit.\nimport oracledb from 'oracledb';\n".to_string()
    }

    fn generate_row_struct(&self, query_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        let mut out = String::new();
        let _ = writeln!(out, "export interface {} {{", struct_name);
        for col in columns {
            let _ = writeln!(out, "\t{}: {};", col.field_name, col.full_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_model_struct(&self, table_name: &str, columns: &[ResolvedColumn]) -> Result<String, ScytheError> {
        let singular = singularize(table_name);
        let name = to_pascal_case(&singular);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql = super::rewrite_pg_placeholders(
            &super::clean_sql_oneline_with_optional(&analyzed.sql, &analyzed.optional_params, &analyzed.params),
            |n| format!(":{n}"),
        );

        let param_list = params
            .iter()
            .map(|p| format!("{}: {}", p.field_name, p.full_type))
            .collect::<Vec<_>>()
            .join(", ");
        let sep = if param_list.is_empty() { "" } else { ", " };

        let bind_array = if params.is_empty() {
            "[]".to_string()
        } else {
            format!(
                "[{}]",
                params
                    .iter()
                    .map(|p| p.field_name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        };

        let has_returning = sql.to_uppercase().contains("RETURNING");

        let mut out = String::new();

        match &analyzed.command {
            QueryCommand::One | QueryCommand::Opt => {
                let _ = writeln!(
                    out,
                    "export async function {}(conn: oracledb.Connection{}{}): Promise<{} | null> {{",
                    func_name, sep, param_list, struct_name
                );

                if has_returning {
                    let out_bind_entries: Vec<String> = columns
                        .iter()
                        .map(|col| {
                            let nt = col.neutral_type.as_str();
                            let oratype = match nt {
                                "int32" | "int64" | "float32" | "float64" | "decimal" => "oracledb.NUMBER",
                                "date" | "datetime" | "datetime_tz" | "time" | "time_tz" => "oracledb.DATE",
                                _ => "oracledb.STRING",
                            };
                            format!("{{ dir: oracledb.BIND_OUT, type: {} }}", oratype)
                        })
                        .collect();
                    let into_clause = columns
                        .iter()
                        .enumerate()
                        .map(|(i, _)| format!(":{}", params.len() + i + 1))
                        .collect::<Vec<_>>()
                        .join(", ");
                    let full_sql = format!("{} INTO {}", sql, into_clause);
                    let all_binds = if params.is_empty() {
                        format!("[{}]", out_bind_entries.join(", "))
                    } else {
                        let input_names: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
                        format!("[{}, {}]", input_names.join(", "), out_bind_entries.join(", "))
                    };
                    let _ = writeln!(
                        out,
                        "\tconst result = await conn.execute(\"{}\", {});",
                        full_sql, all_binds
                    );
                    let _ = writeln!(out, "\tif (!result.outBinds) {{");
                    let _ = writeln!(out, "\t\treturn null;");
                    let _ = writeln!(out, "\t}}");
                    let _ = writeln!(out, "\tconst outBinds = result.outBinds as unknown[][];");
                    let _ = writeln!(out, "\treturn {{");
                    for (i, col) in columns.iter().enumerate() {
                        let _ = writeln!(out, "\t\t{}: outBinds[{}][0] as {},", col.field_name, i, col.lang_type);
                    }
                    let _ = writeln!(out, "\t}};");
                    let _ = write!(out, "}}");
                } else {
                    let _ = writeln!(
                        out,
                        "\tconst result = await conn.execute(\"{}\", {}, {{ outFormat: oracledb.OUT_FORMAT_OBJECT }});",
                        sql, bind_array
                    );
                    let _ = writeln!(out, "\tif (!result.rows || result.rows.length === 0) {{");
                    let _ = writeln!(out, "\t\treturn null;");
                    let _ = writeln!(out, "\t}}");
                    let _ = writeln!(out, "\tconst row = result.rows[0] as Record<string, unknown>;");
                    let _ = writeln!(out, "\treturn {{");
                    for col in columns {
                        let _ = writeln!(
                            out,
                            "\t\t{}: row[\"{}\"] as {},",
                            col.field_name,
                            col.name.to_uppercase(),
                            col.lang_type
                        );
                    }
                    let _ = writeln!(out, "\t}};");
                    let _ = write!(out, "}}");
                }
            }
            QueryCommand::Many => {
                let _ = writeln!(
                    out,
                    "export async function {}(conn: oracledb.Connection{}{}): Promise<{}[]> {{",
                    func_name, sep, param_list, struct_name
                );
                let _ = writeln!(
                    out,
                    "\tconst result = await conn.execute(\"{}\", {}, {{ outFormat: oracledb.OUT_FORMAT_OBJECT }});",
                    sql, bind_array
                );
                let _ = writeln!(out, "\tif (!result.rows) {{");
                let _ = writeln!(out, "\t\treturn [];");
                let _ = writeln!(out, "\t}}");
                let _ = writeln!(out, "\treturn result.rows.map((row: Record<string, unknown>) => ({{",);
                for col in columns {
                    let _ = writeln!(
                        out,
                        "\t\t{}: row[\"{}\"] as {},",
                        col.field_name,
                        col.name.to_uppercase(),
                        col.lang_type
                    );
                }
                let _ = writeln!(out, "\t}}));");
                let _ = write!(out, "}}");
            }
            QueryCommand::Exec => {
                let _ = writeln!(
                    out,
                    "export async function {}(conn: oracledb.Connection{}{}): Promise<void> {{",
                    func_name, sep, param_list
                );
                let _ = writeln!(out, "\tawait conn.execute(\"{}\", {});", sql, bind_array);
                let _ = write!(out, "}}");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                let _ = writeln!(
                    out,
                    "export async function {}(conn: oracledb.Connection{}{}): Promise<number> {{",
                    func_name, sep, param_list
                );
                let _ = writeln!(out, "\tconst result = await conn.execute(\"{}\", {});", sql, bind_array);
                let _ = writeln!(out, "\treturn result.rowsAffected ?? 0;");
                let _ = write!(out, "}}");
            }
            QueryCommand::Batch => {
                let batch_fn_name = format!("{}Batch", func_name);
                let items_type = if params.len() > 1 {
                    let tuple_types: Vec<String> = params.iter().map(|p| p.full_type.clone()).collect();
                    format!("[{}]", tuple_types.join(", "))
                } else if params.len() == 1 {
                    params[0].full_type.clone()
                } else {
                    "number".to_string()
                };
                let _ = writeln!(
                    out,
                    "export async function {}(conn: oracledb.Connection, items: {}[]): Promise<void> {{",
                    batch_fn_name, items_type
                );
                if params.is_empty() {
                    let _ = writeln!(out, "\tfor (let i = 0; i < items.length; i++) {{");
                    let _ = writeln!(out, "\t\tawait conn.execute(\"{}\");", sql);
                    let _ = writeln!(out, "\t}}");
                } else {
                    let _ = writeln!(
                        out,
                        "\tawait conn.executeMany(\"{}\", items.map(item => Array.isArray(item) ? item : [item]));",
                        sql
                    );
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::Grouped => {
                unreachable!("Grouped command is routed through generate_grouped_query_fn, not generate_query_fn")
            }
        }

        Ok(out)
    }

    fn generate_grouped_structs(
        &self,
        parent_struct_name: &str,
        child_struct_name: &str,
        parent_columns: &[ResolvedColumn],
        child_columns: &[ResolvedColumn],
        _key_column: &str,
    ) -> Result<String, ScytheError> {
        Ok(generate_grouped_interface_structs(
            child_struct_name,
            parent_struct_name,
            parent_columns,
            child_columns,
        ))
    }

    fn generate_grouped_query_fn(&self, request: &GroupedQueryFn<'_>) -> Result<String, ScytheError> {
        let analyzed = request.analyzed;
        let parent_struct_name = request.parent_struct_name;
        let child_struct_name = request.child_struct_name;
        let parent_columns = request.parent_columns;
        let child_columns = request.child_columns;
        let params = request.params;
        let key_column = request.key_column;

        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let sql_clean =
            super::clean_sql_oneline_with_optional(&analyzed.sql, &analyzed.optional_params, &analyzed.params);
        let sql = super::rewrite_pg_placeholders(&sql_clean, |n| format!(":{n}"));

        let param_list = params
            .iter()
            .map(|p| format!("{}: {}", p.field_name, p.full_type))
            .collect::<Vec<_>>()
            .join(", ");
        let inline_params = if params.is_empty() {
            "conn: oracledb.Connection".to_string()
        } else {
            format!("conn: oracledb.Connection, {}", param_list)
        };
        let ret = format!("Promise<{parent_struct_name}[]>");

        let mut out = String::new();
        let oneliner = format!("export async function {func_name}({inline_params}): {ret} {{");
        if oneliner.len() <= 80 {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "{oneliner}");
        } else {
            let _ = writeln!(out, "/** Fetch grouped {} rows. */", analyzed.name);
            let _ = writeln!(out, "export async function {func_name}(");
            let _ = writeln!(out, "\tconn: oracledb.Connection,");
            for p in params {
                let _ = writeln!(out, "\t{}: {},", p.field_name, p.full_type);
            }
            let _ = writeln!(out, "): {ret} {{");
        }

        if params.is_empty() {
            let _ = writeln!(out, "\tconst result = await conn.execute(");
            let _ = writeln!(out, "\t\t`{sql}`,");
            let _ = writeln!(out, "\t\t[],");
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            let _ = writeln!(out, "\tconst result = await conn.execute(");
            let _ = writeln!(out, "\t\t`{sql}`,");
            let _ = writeln!(out, "\t\t[{}],", args.join(", "));
        }
        let _ = writeln!(out, "\t\t{{ outFormat: oracledb.OUT_FORMAT_OBJECT }},");
        let _ = writeln!(out, "\t);");
        let _ = writeln!(
            out,
            "\tconst flatRows = (result.rows ?? []) as unknown as Record<string, unknown>[];"
        );

        let fold = generate_ts_grouped_fold_body(
            parent_struct_name,
            child_struct_name,
            parent_columns,
            child_columns,
            key_column,
            |name, ty| format!("row['{}'] as {ty}", name.to_uppercase()),
        );
        out.push_str(&fold);
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        let type_name = enum_type_name(&enum_info.sql_name, &self.manifest.naming);
        let mut out = String::new();
        let values: Vec<String> = enum_info.values.iter().map(|v| format!("\"{}\"", v)).collect();
        let _ = writeln!(out, "export type {} = {};", type_name, values.join(" | "));
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        let _ = writeln!(out, "export interface {} {{", name);
        for field in &composite.fields {
            let ts_type = resolve_type(&field.neutral_type, &self.manifest, false)
                .map(|t| t.into_owned())
                .map_err(|e| {
                    ScytheError::new(ErrorCode::InternalError, format!("composite field type error: {}", e))
                })?;
            let _ = writeln!(out, "\t{}: {};", to_camel_case(&field.name), ts_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }
}

#[cfg(test)]
mod tests {
    use super::TypescriptOracledbBackend;
    use scythe_core::analyzer::{AnalyzedColumn, AnalyzedQuery, GroupByConfig};
    use scythe_core::parser::QueryCommand;

    fn make_grouped_query() -> AnalyzedQuery {
        let parent_cols = vec![
            AnalyzedColumn {
                name: "id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
            },
            AnalyzedColumn {
                name: "name".to_string(),
                neutral_type: "string".to_string(),
                nullable: false,
            },
        ];
        let child_cols = vec![
            AnalyzedColumn {
                name: "order_id".to_string(),
                neutral_type: "int32".to_string(),
                nullable: false,
            },
            AnalyzedColumn {
                name: "total".to_string(),
                neutral_type: "decimal".to_string(),
                nullable: true,
            },
        ];
        let all_cols = [parent_cols.clone(), child_cols.clone()].concat();
        AnalyzedQuery {
            name: "GetUsersWithOrders".to_string(),
            command: QueryCommand::Grouped,
            sql: "SELECT u.id, u.name, o.id AS order_id, o.total FROM users u JOIN orders o ON o.user_id = u.id"
                .to_string(),
            columns: all_cols,
            params: vec![],
            deprecated: None,
            source_table: None,
            composites: vec![],
            enums: vec![],
            optional_params: vec![],
            group_by: Some(GroupByConfig {
                table: "users".to_string(),
                key_column: "id".to_string(),
                parent_columns: parent_cols,
                child_columns: child_cols,
            }),
            custom: vec![],
        }
    }

    #[test]
    fn test_grouped_typescript_oracledb_structs() {
        let backend = TypescriptOracledbBackend::new("oracle").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let row_struct = result.row_struct.as_deref().unwrap();

        assert!(
            row_struct.contains("interface GetUsersWithOrdersChildRow"),
            "missing child; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("interface GetUsersWithOrdersRow"),
            "missing parent; got:\n{row_struct}"
        );
        assert!(
            row_struct.contains("children: GetUsersWithOrdersChildRow[]"),
            "missing children; got:\n{row_struct}"
        );
        let child_pos = row_struct.find("GetUsersWithOrdersChildRow").unwrap();
        let parent_pos = row_struct.find("interface GetUsersWithOrdersRow").unwrap();
        assert!(child_pos < parent_pos, "child must precede parent");
    }

    #[test]
    fn test_grouped_typescript_oracledb_query_fn() {
        let backend = TypescriptOracledbBackend::new("oracle").unwrap();
        let query = make_grouped_query();
        let result = crate::generate_with_backend(&query, &backend).unwrap();
        let query_fn = result.query_fn.as_deref().unwrap();

        assert!(query_fn.contains("getUsersWithOrders"), "missing fn; got:\n{query_fn}");
        assert!(
            query_fn.contains("Promise<GetUsersWithOrdersRow[]>"),
            "wrong return type; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("conn.execute"),
            "must use conn.execute; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("OUT_FORMAT_OBJECT"),
            "must set outFormat; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("row['ID']"),
            "must use UPPERCASE key for Oracle; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("new Map<unknown, GetUsersWithOrdersRow>()"),
            "must use Map; got:\n{query_fn}"
        );
        assert!(
            query_fn.contains("parent.children.push"),
            "must fold children; got:\n{query_fn}"
        );
    }
}
