use std::fmt::Write;
use std::path::Path;

use scythe_backend::manifest::{BackendManifest, load_manifest};
use scythe_backend::naming::{fn_name, row_struct_name, to_camel_case, to_pascal_case};
use scythe_backend::types::resolve_type;

use scythe_core::analyzer::{AnalyzedQuery, CompositeInfo, EnumInfo};
use scythe_core::errors::{ErrorCode, ScytheError};
use scythe_core::parser::QueryCommand;

use crate::backend_trait::{CodegenBackend, ResolvedColumn, ResolvedParam};
use crate::singularize;

const DEFAULT_MANIFEST_TOML: &str = include_str!("../../manifests/typescript-better-sqlite3.toml");

pub struct TypescriptBetterSqlite3Backend {
    manifest: BackendManifest,
}

impl TypescriptBetterSqlite3Backend {
    pub fn new(engine: &str) -> Result<Self, ScytheError> {
        match engine {
            "sqlite" | "sqlite3" => {}
            _ => {
                return Err(ScytheError::new(
                    ErrorCode::InternalError,
                    format!(
                        "typescript-better-sqlite3 only supports SQLite, got engine '{}'",
                        engine
                    ),
                ));
            }
        }
        let manifest_path = Path::new("backends/typescript-better-sqlite3/manifest.toml");
        let manifest = if manifest_path.exists() {
            load_manifest(manifest_path)
                .map_err(|e| ScytheError::new(ErrorCode::InternalError, format!("manifest: {e}")))?
        } else {
            toml::from_str(DEFAULT_MANIFEST_TOML)
                .map_err(|e| ScytheError::new(ErrorCode::InternalError, format!("manifest: {e}")))?
        };
        Ok(Self { manifest })
    }
}

impl CodegenBackend for TypescriptBetterSqlite3Backend {
    fn name(&self) -> &str {
        "typescript-better-sqlite3"
    }

    fn manifest(&self) -> &scythe_backend::manifest::BackendManifest {
        &self.manifest
    }

    fn supported_engines(&self) -> &[&str] {
        &["sqlite"]
    }

    fn file_header(&self) -> String {
        "/** Auto-generated by scythe. Do not edit. */\n\nimport type Database from \"better-sqlite3\";\n"
            .to_string()
    }

    fn generate_row_struct(
        &self,
        query_name: &str,
        columns: &[ResolvedColumn],
    ) -> Result<String, ScytheError> {
        let struct_name = row_struct_name(query_name, &self.manifest.naming);
        let mut out = String::new();
        let _ = writeln!(out, "/** Row type for {} queries. */", query_name);
        let _ = writeln!(out, "export interface {} {{", struct_name);
        for col in columns {
            let _ = writeln!(out, "\t{}: {};", col.field_name, col.full_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }

    fn generate_model_struct(
        &self,
        table_name: &str,
        columns: &[ResolvedColumn],
    ) -> Result<String, ScytheError> {
        let singular = singularize(table_name);
        let name = to_pascal_case(&singular);
        self.generate_row_struct(&name, columns)
    }

    fn generate_query_fn(
        &self,
        analyzed: &AnalyzedQuery,
        struct_name: &str,
        _columns: &[ResolvedColumn],
        params: &[ResolvedParam],
    ) -> Result<String, ScytheError> {
        let func_name = fn_name(&analyzed.name, &self.manifest.naming);
        let mut out = String::new();

        let param_list = params
            .iter()
            .map(|p| format!("{}: {}", p.field_name, p.full_type))
            .collect::<Vec<_>>()
            .join(", ");

        let sql = super::clean_sql(&analyzed.sql);

        let inline_params = if params.is_empty() {
            "db: Database".to_string()
        } else {
            format!("db: Database, {}", param_list)
        };

        // Helper: write function signature (sync, no async)
        let write_fn_sig = |out: &mut String, name: &str, params_inline: &str, ret: &str| {
            let oneliner = format!("export function {}({}): {} {{", name, params_inline, ret);
            if oneliner.len() <= 80 {
                let _ = writeln!(out, "{}", oneliner);
            } else {
                let mut parts = vec!["\tdb: Database".to_string()];
                for p in params {
                    parts.push(format!("\t{}: {}", p.field_name, p.full_type));
                }
                let _ = writeln!(out, "export function {}(", name);
                for part in &parts {
                    let _ = writeln!(out, "{},", part);
                }
                let _ = writeln!(out, "): {} {{", ret);
            }
        };

        // Build param args for .get()/.all()/.run()
        let param_args = if params.is_empty() {
            String::new()
        } else {
            let args: Vec<String> = params.iter().map(|p| p.field_name.clone()).collect();
            args.join(", ")
        };

        match &analyzed.command {
            QueryCommand::One => {
                let _ = writeln!(out, "/** Fetch a single {} or null. */", struct_name);
                let ret = format!("{} | null", struct_name);
                write_fn_sig(&mut out, &func_name, &inline_params, &ret);
                let _ = writeln!(out, "\tconst stmt = db.prepare(`{}`);", sql);
                if params.is_empty() {
                    let _ = writeln!(
                        out,
                        "\tconst row = stmt.get() as {} | undefined;",
                        struct_name
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "\tconst row = stmt.get({}) as {} | undefined;",
                        param_args, struct_name
                    );
                }
                let _ = writeln!(out, "\treturn row ?? null;");
                let _ = write!(out, "}}");
            }
            QueryCommand::Many | QueryCommand::Batch => {
                let _ = writeln!(out, "/** Fetch all {} rows. */", struct_name);
                let ret = format!("{}[]", struct_name);
                write_fn_sig(&mut out, &func_name, &inline_params, &ret);
                let _ = writeln!(out, "\tconst stmt = db.prepare(`{}`);", sql);
                if params.is_empty() {
                    let _ = writeln!(out, "\treturn stmt.all() as {}[];", struct_name);
                } else {
                    let _ = writeln!(
                        out,
                        "\treturn stmt.all({}) as {}[];",
                        param_args, struct_name
                    );
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::Exec => {
                let _ = writeln!(out, "/** Execute a query returning no rows. */");
                write_fn_sig(&mut out, &func_name, &inline_params, "void");
                let _ = writeln!(out, "\tconst stmt = db.prepare(`{}`);", sql);
                if params.is_empty() {
                    let _ = writeln!(out, "\tstmt.run();");
                } else {
                    let _ = writeln!(out, "\tstmt.run({});", param_args);
                }
                let _ = write!(out, "}}");
            }
            QueryCommand::ExecResult | QueryCommand::ExecRows => {
                let _ = writeln!(
                    out,
                    "/** Execute a query and return the number of affected rows. */"
                );
                write_fn_sig(&mut out, &func_name, &inline_params, "number");
                let _ = writeln!(out, "\tconst stmt = db.prepare(`{}`);", sql);
                if params.is_empty() {
                    let _ = writeln!(out, "\tconst result = stmt.run();");
                } else {
                    let _ = writeln!(out, "\tconst result = stmt.run({});", param_args);
                }
                let _ = writeln!(out, "\treturn result.changes;");
                let _ = write!(out, "}}");
            }
        }

        Ok(out)
    }

    fn generate_enum_def(&self, enum_info: &EnumInfo) -> Result<String, ScytheError> {
        // SQLite has no native ENUM type; generate a string union type instead
        let type_name = to_pascal_case(&enum_info.sql_name);
        let mut out = String::new();
        let variants: Vec<String> = enum_info
            .values
            .iter()
            .map(|v| format!("\"{}\"", v))
            .collect();
        let _ = write!(out, "export type {} = {};", type_name, variants.join(" | "));
        Ok(out)
    }

    fn generate_composite_def(&self, composite: &CompositeInfo) -> Result<String, ScytheError> {
        let name = to_pascal_case(&composite.sql_name);
        let mut out = String::new();
        let _ = writeln!(out, "/** Composite type {}. */", composite.sql_name);
        let _ = writeln!(out, "export interface {} {{", name);
        for field in &composite.fields {
            let ts_type = resolve_type(&field.neutral_type, &self.manifest, false)
                .map(|t| t.into_owned())
                .map_err(|e| {
                    ScytheError::new(
                        ErrorCode::InternalError,
                        format!("composite field type error: {}", e),
                    )
                })?;
            let _ = writeln!(out, "\t{}: {};", to_camel_case(&field.name), ts_type);
        }
        let _ = write!(out, "}}");
        Ok(out)
    }
}
