// Auto-generated by scythe. Do not edit.
#![allow(dead_code, unused_imports, clippy::needless_question_mark, clippy::redundant_closure)]

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct CreateOrderRow {
    pub id: i32,
    pub user_id: i32,
    pub total: rust_decimal::Decimal,
    pub notes: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}



#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetOrdersByUserRow {
    pub id: i32,
    pub total: rust_decimal::Decimal,
    pub notes: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
}



#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetOrderTotalRow {
    pub total_sum: Option<rust_decimal::Decimal>,
}





#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetUserByIdRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
    pub status: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
}



#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListActiveUsersRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
}



#[derive(Debug, Clone, sqlx::FromRow)]
pub struct CreateUserRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
    pub status: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
}







#[derive(Debug, Clone, sqlx::FromRow)]
pub struct SearchUsersRow {
    pub id: i32,
    pub name: String,
    pub email: Option<String>,
}
