mod fixture;

use clap::Parser;
use fixture::{ExpectedCatalog, ExpectedQuery, Fixture};
use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

/// Scythe test generator -- turns JSON fixture files into Rust integration tests.
#[derive(Parser, Debug)]
#[command(name = "test-generator", version, about)]
struct Cli {
    /// Directory containing JSON fixture files.
    #[arg(long, default_value = "testing_data")]
    fixtures: PathBuf,

    /// Output directory for generated test files.
    #[arg(long, default_value = "tests/generated")]
    output: PathBuf,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    if !cli.fixtures.is_dir() {
        return Err(format!(
            "fixtures directory does not exist: {}",
            cli.fixtures.display()
        )
        .into());
    }

    let fixtures = fixture::load_fixtures(&cli.fixtures)?;
    if fixtures.is_empty() {
        eprintln!(
            "warning: no fixture files found in {}",
            cli.fixtures.display()
        );
        return Ok(());
    }

    // Group by top-level category (first path component of `category`).
    let mut groups: BTreeMap<String, Vec<&Fixture>> = BTreeMap::new();
    for f in &fixtures {
        let top = f
            .category
            .split('/')
            .next()
            .unwrap_or(&f.category)
            .to_string();
        groups.entry(top).or_default().push(f);
    }

    fs::create_dir_all(&cli.output)?;

    let mut module_names: Vec<String> = Vec::new();

    for (category, category_fixtures) in &groups {
        let module_name = sanitize_module_name(category);
        let file_name = format!("test_{}.rs", module_name);
        let file_path = cli.output.join(&file_name);

        let code = generate_test_file(category, category_fixtures);
        fs::write(&file_path, &code)?;

        println!("wrote {}", file_path.display());
        module_names.push(module_name);
    }

    // Generate mod.rs
    let mod_path = cli.output.join("mod.rs");
    let mod_code = generate_mod_rs(&module_names);
    fs::write(&mod_path, &mod_code)?;
    println!("wrote {}", mod_path.display());

    println!(
        "generated {} test file(s) from {} fixture(s)",
        module_names.len(),
        fixtures.len()
    );

    if !fixtures.is_empty() && module_names.is_empty() {
        return Err("fixtures were loaded but no tests were generated".into());
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

fn generate_mod_rs(module_names: &[String]) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("// Auto-generated by test-generator. Do not edit.\n\n");
    for name in module_names {
        let _ = writeln!(out, "mod test_{};", name);
    }
    out
}

fn generate_test_file(category: &str, fixtures: &[&Fixture]) -> String {
    let mut out = String::with_capacity(64 * 1024);
    out.push_str("// Auto-generated by test-generator. Do not edit.\n");
    let _ = writeln!(out, "// Category: {}\n", category);
    // Codegen verification imports (used by query tests)
    out.push_str("#[allow(unused_imports)]\nuse scythe_codegen as _codegen;\n");
    out.push_str("#[allow(unused_imports)]\nuse syn as _syn;\n\n");

    for fixture in fixtures {
        out.push_str(&generate_single_test(fixture));
        out.push('\n');
    }

    out
}

fn generate_single_test(fixture: &Fixture) -> String {
    let file_path_comment = fixture.file_path.as_deref().unwrap_or("<unknown>");

    let expected = &fixture.expected;
    let is_error = !expected.success;
    let is_lint = fixture.category.starts_with("lint/");

    if is_error {
        generate_error_test(fixture, file_path_comment)
    } else if is_lint {
        generate_lint_test(fixture, file_path_comment)
    } else if fixture.query_sql.is_some() {
        generate_query_test(fixture, file_path_comment)
    } else {
        generate_catalog_test(fixture, file_path_comment)
    }
}

// -- Catalog-only test ------------------------------------------------------

fn generate_catalog_test(fixture: &Fixture, file_path: &str) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("#[test]\n");
    let _ = writeln!(out, "fn test_{}() {{", fixture.name);
    let _ = writeln!(out, "    // From: {}", file_path);
    let _ = writeln!(out, "    // {:?}", fixture.description);

    out.push_str(&format_schema_sql(&fixture.schema_sql));
    out.push_str(
        "    let catalog = scythe_core::catalog::Catalog::from_ddl(schema_sql).unwrap();\n\n",
    );

    if let Some(ref catalog) = fixture.expected.catalog {
        out.push_str(&generate_catalog_assertions(catalog));
    }

    out.push_str("}\n");
    out
}

// -- Query test -------------------------------------------------------------

fn generate_query_test(fixture: &Fixture, file_path: &str) -> String {
    let mut out = String::with_capacity(8192);
    out.push_str("#[test]\n");
    let _ = writeln!(out, "fn test_{}() {{", fixture.name);
    let _ = writeln!(out, "    // From: {}", file_path);
    let _ = writeln!(out, "    // {:?}", fixture.description);

    out.push_str(&format_schema_sql(&fixture.schema_sql));

    let query_sql = fixture.query_sql.as_deref().unwrap_or("");
    let _ = writeln!(out, "    let query_sql = {:?};\n", query_sql);

    out.push_str(
        "    let catalog = scythe_core::catalog::Catalog::from_ddl(schema_sql).unwrap();\n",
    );
    out.push_str("    let query = scythe_core::parser::parse_query(query_sql).unwrap();\n");
    out.push_str(
        "    let analyzed = scythe_core::analyzer::analyze(&catalog, &query).unwrap();\n\n",
    );

    // Analysis assertions (types, nullability, params)
    if let Some(ref catalog) = fixture.expected.catalog {
        out.push_str(&generate_catalog_assertions(catalog));
    }

    if let Some(ref query) = fixture.expected.query {
        out.push_str(&generate_query_assertions(query));
    }

    // Codegen verification — test all backends produce valid output
    let command = fixture
        .expected
        .query
        .as_ref()
        .map(|q| q.command.to_string())
        .unwrap_or_default();

    out.push_str("    // Codegen verification: all backends should produce valid output\n");
    out.push_str("    let all_backends = [\n");
    out.push_str("        \"rust-sqlx\",\n");
    out.push_str("        \"rust-tokio-postgres\",\n");
    out.push_str("        \"python-psycopg3\",\n");
    out.push_str("        \"python-asyncpg\",\n");
    out.push_str("        \"typescript-postgres\",\n");
    out.push_str("        \"typescript-pg\",\n");
    out.push_str("        \"go-pgx\",\n");
    out.push_str("        \"java-jdbc\",\n");
    out.push_str("        \"kotlin-jdbc\",\n");
    out.push_str("        \"csharp-npgsql\",\n");
    out.push_str("        \"elixir-postgrex\",\n");
    out.push_str("        \"ruby-pg\",\n");
    out.push_str("        \"ruby-trilogy\",\n");
    out.push_str("        \"php-pdo\",\n");
    out.push_str("    ];\n");
    out.push_str("    for backend_name in &all_backends {\n");
    out.push_str(
        "        let backend = match scythe_codegen::get_backend(backend_name, \"postgresql\") {\n",
    );
    out.push_str("            Ok(b) => b,\n");
    out.push_str("            Err(_) => continue, // skip unregistered backends\n");
    out.push_str("        };\n");
    out.push_str("        if let Ok(generated) = scythe_codegen::generate_with_backend(&analyzed, &*backend) {\n");
    out.push_str("                let header = backend.file_header();\n");
    out.push_str("                let mut code = if header.is_empty() {\n");
    out.push_str("                    String::from(\"#![allow(dead_code, unused_imports)]\\n\")\n");
    out.push_str("                } else {\n");
    out.push_str("                    let mut h = header; h.push('\\n'); h\n");
    out.push_str("                };\n");
    out.push_str("                if let Some(ref s) = generated.enum_def { code.push_str(s); code.push('\\n'); }\n");
    out.push_str("                if let Some(ref s) = generated.model_struct { code.push_str(s); code.push('\\n'); }\n");
    out.push_str("                if let Some(ref s) = generated.row_struct { code.push_str(s); code.push('\\n'); }\n");
    out.push_str("                if let Some(ref s) = generated.query_fn { code.push_str(s); code.push('\\n'); }\n");
    out.push_str("                if code.lines().count() > 1 {\n");
    out.push_str("                    // Only validate Rust syntax with syn for Rust backends\n");
    out.push_str("                    if *backend_name == \"rust-sqlx\" || *backend_name == \"rust-tokio-postgres\" {\n");
    out.push_str("                        assert!(\n");
    out.push_str("                            syn::parse_file(&code).is_ok(),\n");
    let _ = writeln!(
        out,
        "                            \"backend {{}} generated invalid Rust for {{}}\", backend_name, {:?}",
        fixture.name
    );
    out.push_str("                        );\n");
    out.push_str("                    } else {\n");
    out.push_str("                        // Structural validation for non-Rust backends\n");
    out.push_str("                        let errors = scythe_codegen::validation::validate_structural(&code, backend_name);\n");
    out.push_str("                        assert!(\n");
    out.push_str("                            errors.is_empty(),\n");
    let _ = writeln!(
        out,
        "                            \"backend {{}} structural validation failed for {{}}: {{:?}}\", backend_name, {:?}, errors",
        fixture.name
    );
    out.push_str("                        );\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");

    // Structural checks
    if command == "one" || command == "many" {
        out.push_str("                assert!(\n");
        out.push_str("                    generated.row_struct.is_some() || generated.model_struct.is_some(),\n");
        let _ = writeln!(
            out,
            "                    \"backend {{}} should produce a struct for {{}}\", backend_name, {:?}",
            fixture.name
        );
        out.push_str("                );\n");
    }
    out.push_str("                assert!(\n");
    out.push_str("                    generated.query_fn.is_some(),\n");
    let _ = writeln!(
        out,
        "                    \"backend {{}} should produce query_fn for {{}}\", backend_name, {:?}",
        fixture.name
    );
    out.push_str("                );\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    out.push_str("}\n");
    out
}

// -- Lint test --------------------------------------------------------------

fn generate_lint_test(fixture: &Fixture, file_path: &str) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("#[test]\n");
    let _ = writeln!(out, "fn test_{}() {{", fixture.name);
    let _ = writeln!(out, "    // From: {}", file_path);
    let _ = writeln!(out, "    // {:?}", fixture.description);

    out.push_str(&format_schema_sql(&fixture.schema_sql));

    out.push_str(
        "    let catalog = scythe_core::catalog::Catalog::from_ddl(schema_sql).unwrap();\n",
    );
    out.push_str("    let registry = scythe_lint::default_registry();\n");
    out.push_str("    let engine = scythe_lint::LintEngine::new(registry);\n");
    out.push_str("    let mut _violations: Vec<(scythe_lint::Violation, scythe_lint::Severity)> = Vec::new();\n\n");

    // Always run catalog-level checks
    out.push_str("    _violations.extend(engine.check_catalog(&catalog));\n\n");

    if let Some(ref query_sql) = fixture.query_sql {
        let _ = writeln!(out, "    let query_sql = {:?};", query_sql);
        // Lint tests may have multiple queries — try to parse single query
        out.push_str("    if let Ok(query) = scythe_core::parser::parse_query(query_sql) {\n");
        out.push_str(
            "        if let Ok(analyzed) = scythe_core::analyzer::analyze(&catalog, &query) {\n",
        );
        out.push_str("            let ctx = scythe_lint::LintContext {\n");
        out.push_str("                sql: &query.sql,\n");
        out.push_str("                stmt: &query.stmt,\n");
        out.push_str("                analyzed: &analyzed,\n");
        out.push_str("                catalog: &catalog,\n");
        out.push_str("                annotations: &query.annotations,\n");
        out.push_str("            };\n");
        out.push_str("            _violations.extend(engine.check_query(&ctx));\n");

        out.push_str("        }\n");
        out.push_str("    }\n");
    }

    // Check expected lint results (outside if-let blocks so catalog checks are always verified)
    if let Some(ref lint) = fixture.expected.lint {
        if lint.violations.is_empty() {
            out.push_str("    assert!(_violations.is_empty(), \"expected no lint violations but got {}\", _violations.len());\n");
        } else {
            let _ = writeln!(
                out,
                "    assert!(!_violations.is_empty(), \"expected lint violations for {}\");",
                fixture.name
            );
            for v in &lint.violations {
                let _ = writeln!(
                    out,
                    "    assert!(_violations.iter().any(|v| v.0.rule_id.contains({code:?})), \"expected violation {code}\");",
                    code = v.rule_code
                );
            }
        }
    }

    out.push_str("}\n");
    out
}

// -- Error test -------------------------------------------------------------

fn generate_error_test(fixture: &Fixture, file_path: &str) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("#[test]\n");
    let _ = writeln!(out, "fn test_{}() {{", fixture.name);
    let _ = writeln!(out, "    // From: {}", file_path);
    let _ = writeln!(out, "    // {:?}", fixture.description);

    out.push_str(&format_schema_sql(&fixture.schema_sql));

    let has_query = fixture.query_sql.is_some();

    if has_query {
        let query_sql = fixture.query_sql.as_deref().unwrap_or("");
        let _ = writeln!(out, "    let query_sql = {:?};\n", query_sql);
        out.push_str(
            "    let catalog_result = scythe_core::catalog::Catalog::from_ddl(schema_sql);\n",
        );
        out.push_str("    if let Ok(catalog) = catalog_result {\n");
        out.push_str("        let query_result = scythe_core::parser::parse_query(query_sql);\n");
        out.push_str("        if let Ok(query) = query_result {\n");
        out.push_str(
            "            let result = scythe_core::analyzer::analyze(&catalog, &query);\n",
        );
        out.push_str("            assert!(result.is_err(), \"expected analysis to fail\");\n");

        if let Some(ref error) = fixture.expected.error {
            out.push_str(&generate_error_assertions_nested("result", error, 12));
        }

        out.push_str("        } else {\n");
        out.push_str("            // Parse failed -- that counts as expected failure.\n");

        if let Some(ref error) = fixture.expected.error {
            out.push_str(&generate_error_assertions_nested("query_result", error, 12));
        }

        out.push_str("        }\n");
        out.push_str("    } else {\n");
        out.push_str("        // DDL processing failed -- that counts as expected failure.\n");

        if let Some(ref error) = fixture.expected.error {
            out.push_str(&generate_error_assertions_nested(
                "catalog_result",
                error,
                8,
            ));
        }

        out.push_str("    }\n");
    } else {
        // Catalog-only error test.
        out.push_str("    let result = scythe_core::catalog::Catalog::from_ddl(schema_sql);\n");
        out.push_str("    assert!(result.is_err(), \"expected DDL processing to fail\");\n");

        if let Some(ref error) = fixture.expected.error {
            out.push_str(&generate_error_assertions_nested("result", error, 4));
        }
    }

    out.push_str("}\n");
    out
}

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

fn generate_catalog_assertions(catalog: &ExpectedCatalog) -> String {
    let mut out = String::with_capacity(4096);

    // Table assertions
    for (table_name, table) in &catalog.tables {
        let _ = writeln!(out, "    // Assert table: {}", table_name);
        let _ = writeln!(
            out,
            "    let table_{clean} = catalog.get_table({name:?}).expect(\"table {name} should exist\");",
            clean = sanitize_ident(table_name),
            name = table_name,
        );
        let _ = writeln!(
            out,
            "    assert_eq!(table_{}.columns.len(), {}, \"column count for table {}\");",
            sanitize_ident(table_name),
            table.columns.len(),
            table_name,
        );

        for (i, col) in table.columns.iter().enumerate() {
            let tvar = sanitize_ident(table_name);
            let _ = writeln!(
                out,
                "    assert_eq!(table_{tvar}.columns[{i}].name, {name:?}, \"column name\");",
                tvar = tvar,
                i = i,
                name = col.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(table_{tvar}.columns[{i}].sql_type, {sql_type:?}, \"column sql_type for {col_name}\");",
                tvar = tvar,
                i = i,
                sql_type = col.sql_type,
                col_name = col.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(table_{tvar}.columns[{i}].nullable, {nullable}, \"column nullable for {col_name}\");",
                tvar = tvar,
                i = i,
                nullable = col.nullable,
                col_name = col.name,
            );

            if let Some(ref default) = col.default {
                let _ = writeln!(
                    out,
                    "    assert_eq!(table_{tvar}.columns[{i}].default.as_deref(), Some({default:?}), \"column default for {col_name}\");",
                    tvar = tvar,
                    i = i,
                    default = default,
                    col_name = col.name,
                );
            }

            if let Some(pk) = col.primary_key {
                let _ = writeln!(
                    out,
                    "    assert_eq!(table_{tvar}.columns[{i}].primary_key, {pk}, \"column primary_key for {col_name}\");",
                    tvar = tvar,
                    i = i,
                    pk = pk,
                    col_name = col.name,
                );
            }
        }
        out.push('\n');
    }

    // Enum assertions
    for (enum_name, enum_def) in &catalog.enums {
        let _ = writeln!(out, "    // Assert enum: {}", enum_name);
        let _ = writeln!(
            out,
            "    let enum_{clean} = catalog.get_enum({name:?}).expect(\"enum {name} should exist\");",
            clean = sanitize_ident(enum_name),
            name = enum_name,
        );
        let _ = writeln!(
            out,
            "    assert_eq!(enum_{clean}.values, vec![{values}], \"enum values for {name}\");",
            clean = sanitize_ident(enum_name),
            values = enum_def
                .values
                .iter()
                .map(|v| format!("{:?}", v))
                .collect::<Vec<_>>()
                .join(", "),
            name = enum_name,
        );
        out.push('\n');
    }

    // Composite assertions
    for (comp_name, comp) in &catalog.composites {
        let _ = writeln!(out, "    // Assert composite: {}", comp_name);
        let _ = writeln!(
            out,
            "    let comp_{clean} = catalog.get_composite({name:?}).expect(\"composite {name} should exist\");",
            clean = sanitize_ident(comp_name),
            name = comp_name,
        );
        let _ = writeln!(
            out,
            "    assert_eq!(comp_{clean}.fields.len(), {len}, \"field count for composite {name}\");",
            clean = sanitize_ident(comp_name),
            len = comp.fields.len(),
            name = comp_name,
        );

        for (i, field) in comp.fields.iter().enumerate() {
            let cvar = sanitize_ident(comp_name);
            let _ = writeln!(
                out,
                "    assert_eq!(comp_{cvar}.fields[{i}].name, {name:?}, \"composite field name\");",
                cvar = cvar,
                i = i,
                name = field.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(comp_{cvar}.fields[{i}].sql_type, {sql_type:?}, \"composite field sql_type for {field_name}\");",
                cvar = cvar,
                i = i,
                sql_type = field.sql_type,
                field_name = field.name,
            );
        }
        out.push('\n');
    }

    out
}

fn generate_query_assertions(query: &ExpectedQuery) -> String {
    let mut out = String::with_capacity(4096);

    let _ = writeln!(
        out,
        "    assert_eq!(analyzed.name, {:?}, \"query name\");",
        query.name,
    );
    let _ = writeln!(
        out,
        "    assert_eq!(analyzed.command.to_string(), {:?}, \"query command\");",
        query.command.to_string(),
    );

    if !query.params.is_empty() {
        let _ = writeln!(
            out,
            "    assert_eq!(analyzed.params.len(), {}, \"param count\");",
            query.params.len(),
        );
        for (i, param) in query.params.iter().enumerate() {
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.params[{i}].name, {name:?}, \"param name\");",
                i = i,
                name = param.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.params[{i}].neutral_type, {neutral_type:?}, \"param neutral_type for {pname}\");",
                i = i,
                neutral_type = param.neutral_type,
                pname = param.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.params[{i}].nullable, {nullable}, \"param nullable for {pname}\");",
                i = i,
                nullable = param.nullable,
                pname = param.name,
            );
            if let Some(position) = param.position {
                let _ = writeln!(
                    out,
                    "    assert_eq!(analyzed.params[{i}].position, {position}, \"param position for {pname}\");",
                    i = i,
                    position = position,
                    pname = param.name,
                );
            }
        }
    }

    if !query.columns.is_empty() {
        let _ = writeln!(
            out,
            "    assert_eq!(analyzed.columns.len(), {}, \"column count\");",
            query.columns.len(),
        );
        for (i, col) in query.columns.iter().enumerate() {
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.columns[{i}].name, {name:?}, \"column name\");",
                i = i,
                name = col.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.columns[{i}].neutral_type, {neutral_type:?}, \"column neutral_type for {cname}\");",
                i = i,
                neutral_type = col.neutral_type,
                cname = col.name,
            );
            let _ = writeln!(
                out,
                "    assert_eq!(analyzed.columns[{i}].nullable, {nullable}, \"column nullable for {cname}\");",
                i = i,
                nullable = col.nullable,
                cname = col.name,
            );
        }
    }

    out.push('\n');
    out
}

fn generate_error_assertions_nested(
    result_var: &str,
    error: &fixture::ExpectedError,
    indent: usize,
) -> String {
    let mut out = String::with_capacity(4096);
    let pad = " ".repeat(indent);

    let _ = writeln!(
        out,
        "{pad}let err = {var}.unwrap_err();",
        pad = pad,
        var = result_var,
    );
    let _ = writeln!(out, "{pad}let err_msg = err.to_string();", pad = pad,);

    if let Some(ref code) = error.code {
        let _ = writeln!(
            out,
            "{pad}assert!(err_msg.contains({code:?}), \"error should contain code {{:?}}, got: {{}}\", {code:?}, err_msg);",
            pad = pad,
            code = code,
        );
    }

    if let Some(ref msg) = error.message_contains {
        let _ = writeln!(
            out,
            "{pad}assert!(err_msg.contains({msg:?}), \"error should contain {{:?}}, got: {{}}\", {msg:?}, err_msg);",
            pad = pad,
            msg = msg,
        );
    }

    out
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

fn format_schema_sql(stmts: &[String]) -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("    let schema_sql = &[\n");
    for stmt in stmts {
        let _ = writeln!(out, "        {:?},", stmt);
    }
    out.push_str("    ];\n\n");
    out
}

fn sanitize_module_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .to_lowercase()
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .to_lowercase()
}
