[scythe]
version = "1"

[[sql]]
name = "main"
engine = "redshift"
schema = ["../sql/redshift/schema.sql"]
queries = ["../sql/redshift/queries/*.sql"]

[[sql.gen]]
backend = "typescript-postgres"
output = "generated"
