[scythe]
version = "1"

[[sql]]
name = "main"
engine = "snowflake"
schema = ["../sql/snowflake/schema.sql"]
queries = ["../sql/snowflake/queries/*.sql"]

[[sql.gen]]
backend = "java-jdbc"
output = "src/main/java/generated"
