//! Integration tests that exercise the scythe CLI binary via std::process::Command.

use std::path::{Path, PathBuf};
use std::process::Command;

fn scythe_bin() -> Command {
    Command::new(env!("CARGO_BIN_EXE_scythe"))
}

/// Returns the workspace root (two levels up from crate manifest dir).
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn schema_dir(relative: &str) -> PathBuf {
    workspace_root().join("tests/schemas").join(relative)
}

#[test]
fn test_help_exits_zero() {
    let output = scythe_bin()
        .arg("--help")
        .output()
        .expect("failed to run scythe --help");

    assert!(output.status.success(), "scythe --help should exit 0");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("SQL-to-code") || stdout.contains("scythe"),
        "help output should mention scythe"
    );
}

#[test]
fn test_version_exits_zero() {
    let output = scythe_bin()
        .arg("--version")
        .output()
        .expect("failed to run scythe --version");

    assert!(output.status.success(), "scythe --version should exit 0");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("scythe"), "version output should contain 'scythe'");
}

#[test]
fn test_check_basemind_exits_zero() {
    let dir = schema_dir("simple/basemind");
    let output = scythe_bin()
        .args(["check", "--config", "scythe.toml"])
        .current_dir(&dir)
        .output()
        .expect("failed to run scythe check");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "scythe check on basemind should exit 0.\nstderr: {}",
        stderr
    );
    assert!(
        stderr.contains("Check passed") || stderr.contains("valid") || stderr.contains("All queries valid"),
        "check should report success.\nstderr: {}",
        stderr
    );
}

#[test]
fn test_check_pagila_exits_zero() {
    let dir = schema_dir("medium/pagila");
    let output = scythe_bin()
        .args(["check", "--config", "scythe.toml"])
        .current_dir(&dir)
        .output()
        .expect("failed to run scythe check");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "scythe check on pagila should exit 0.\nstderr: {}",
        stderr
    );
}

#[test]
fn test_generate_writes_file() {
    let dir = schema_dir("simple/basemind");
    let temp = tempfile::TempDir::new().unwrap();
    let output_dir = temp.path().join("generated");

    let config_content = format!(
        r#"[scythe]
version = "1"

[[sql]]
name = "test"
engine = "postgresql"
schema = ["schema.sql"]
queries = ["queries/*.sql"]
output = "{}"
"#,
        output_dir.display()
    );

    let config_path = temp.path().join("scythe.toml");
    std::fs::write(&config_path, &config_content).unwrap();

    let output = scythe_bin()
        .args(["generate", "--config", config_path.to_str().unwrap()])
        .current_dir(&dir)
        .output()
        .expect("failed to run scythe generate");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "scythe generate should exit 0.\nstderr: {}",
        stderr
    );

    let generated_file = output_dir.join("queries.rs");
    assert!(
        generated_file.exists(),
        "should create queries.rs at {}",
        generated_file.display()
    );

    let content = std::fs::read_to_string(&generated_file).unwrap();
    assert!(
        content.contains("Auto-generated by scythe"),
        "generated file should have scythe header"
    );
    assert!(
        content.len() > 100,
        "generated file should have substantial content, got {} bytes",
        content.len()
    );
}

#[test]
fn test_generate_pagila_writes_file() {
    let dir = schema_dir("medium/pagila");
    let temp = tempfile::TempDir::new().unwrap();
    let output_dir = temp.path().join("generated");

    let config_content = format!(
        r#"[scythe]
version = "1"

[[sql]]
name = "pagila"
engine = "postgresql"
schema = ["schema.sql"]
queries = ["queries/customers.sql", "queries/rentals.sql"]
output = "{}"
"#,
        output_dir.display()
    );

    let config_path = temp.path().join("scythe.toml");
    std::fs::write(&config_path, &config_content).unwrap();

    let output = scythe_bin()
        .args(["generate", "--config", config_path.to_str().unwrap()])
        .current_dir(&dir)
        .output()
        .expect("failed to run scythe generate");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success(),
        "scythe generate on pagila should exit 0.\nstderr: {}",
        stderr
    );

    let generated_file = output_dir.join("queries.rs");
    assert!(generated_file.exists(), "should create queries.rs for pagila");

    let content = std::fs::read_to_string(&generated_file).unwrap();
    assert!(
        content.len() > 500,
        "pagila should generate substantial code, got {} bytes",
        content.len()
    );
}

#[test]
fn test_missing_config_exits_nonzero() {
    let output = scythe_bin()
        .args(["check", "--config", "nonexistent.toml"])
        .output()
        .expect("failed to run scythe check");

    assert!(!output.status.success(), "scythe check with missing config should fail");
}

#[test]
fn test_no_subcommand_exits_nonzero() {
    let output = scythe_bin().output().expect("failed to run scythe");

    assert!(!output.status.success(), "scythe with no subcommand should fail");
}

/// Write a small SQL file that fires SC-SEC02 (GRANT ALL) and returns its path.
fn write_grant_all_sql(temp: &tempfile::TempDir) -> PathBuf {
    let sql_path = temp.path().join("grant_all.sql");
    std::fs::write(&sql_path, "GRANT ALL ON users TO bob;\n").unwrap();
    sql_path
}

#[test]
fn test_audit_list_rules_exits_zero_and_shows_sec01() {
    let output = scythe_bin()
        .args(["audit", "--list-rules"])
        .output()
        .expect("failed to run scythe audit --list-rules");

    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        output.status.success(),
        "audit --list-rules should exit 0; stdout: {stdout}"
    );
    assert!(
        stdout.contains("SC-SEC01") && stdout.contains("SC-SEC11"),
        "rule catalog must include SC-SEC01..11; got: {stdout}"
    );
    assert!(
        stdout.contains("[security]"),
        "rule catalog must be grouped by category; got: {stdout}"
    );
}

#[test]
fn test_audit_explain_unknown_rule_returns_error() {
    let output = scythe_bin()
        .args(["audit", "--explain", "DOES-NOT-EXIST"])
        .output()
        .expect("failed to run scythe audit --explain");

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !output.status.success(),
        "unknown rule id must exit non-zero; stderr: {stderr}"
    );
    assert!(
        stderr.contains("DOES-NOT-EXIST") && stderr.contains("--list-rules"),
        "error must name the offending id and hint --list-rules; got: {stderr}"
    );
}

#[test]
fn test_audit_exit_zero_overrides_error_exit_code() {
    let temp = tempfile::TempDir::new().unwrap();
    let sql_path = write_grant_all_sql(&temp);

    let base = scythe_bin()
        .args(["audit", sql_path.to_str().unwrap()])
        .output()
        .expect("audit run");
    assert_eq!(
        base.status.code(),
        Some(2),
        "GRANT ALL must yield audit exit code 2; stderr: {}",
        String::from_utf8_lossy(&base.stderr)
    );

    let lenient = scythe_bin()
        .args(["audit", "--exit-zero", sql_path.to_str().unwrap()])
        .output()
        .expect("audit run with --exit-zero");
    assert!(
        lenient.status.success(),
        "--exit-zero must produce exit 0 even with errors; stderr: {}",
        String::from_utf8_lossy(&lenient.stderr)
    );
    let stdout = String::from_utf8_lossy(&lenient.stdout);
    assert!(
        stdout.contains("SC-SEC02"),
        "finding must still be emitted under --exit-zero; got: {stdout}"
    );
}

#[test]
fn test_audit_output_file_writes_sarif() {
    let temp = tempfile::TempDir::new().unwrap();
    let sql_path = write_grant_all_sql(&temp);
    let out_path = temp.path().join("audit.sarif");

    let output = scythe_bin()
        .args([
            "audit",
            "--format",
            "sarif",
            "-o",
            out_path.to_str().unwrap(),
            "--exit-zero",
            sql_path.to_str().unwrap(),
        ])
        .output()
        .expect("audit run with -o");
    assert!(
        output.status.success(),
        "audit with -o + --exit-zero should exit 0; stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let sarif = std::fs::read_to_string(&out_path).expect("read sarif output");
    assert!(
        sarif.contains("\"$schema\"") && sarif.contains("\"2.1.0\""),
        "output file must contain SARIF 2.1.0 envelope; got: {sarif}"
    );
}

#[test]
fn test_audit_ignore_suppressions_resurfaces_finding() {
    let temp = tempfile::TempDir::new().unwrap();
    let sql_path = temp.path().join("suppressed.sql");
    std::fs::write(
        &sql_path,
        "-- scythe-audit: ignore[SC-SEC02]\nGRANT ALL ON users TO bob;\n",
    )
    .unwrap();

    let suppressed = scythe_bin()
        .args(["audit", sql_path.to_str().unwrap()])
        .output()
        .expect("audit run");
    assert!(
        suppressed.status.success(),
        "suppressed run should exit 0; stderr: {}",
        String::from_utf8_lossy(&suppressed.stderr)
    );

    let strict = scythe_bin()
        .args(["audit", "--ignore-suppressions", sql_path.to_str().unwrap()])
        .output()
        .expect("audit run with --ignore-suppressions");
    assert_eq!(
        strict.status.code(),
        Some(2),
        "strict run must surface the finding and exit 2; stderr: {}",
        String::from_utf8_lossy(&strict.stderr)
    );
    let stdout = String::from_utf8_lossy(&strict.stdout);
    assert!(
        stdout.contains("SC-SEC02"),
        "strict run must emit SC-SEC02; got: {stdout}"
    );
}

#[test]
fn test_audit_severity_filter_drops_warnings() {
    let temp = tempfile::TempDir::new().unwrap();
    let sql_path = temp.path().join("mixed.sql");
    std::fs::write(
        &sql_path,
        "GRANT ALL ON users TO bob;\nSELECT * FROM users WHERE name LIKE '%abc%';\n",
    )
    .unwrap();

    let output = scythe_bin()
        .args([
            "audit",
            "--severity",
            "error",
            "--exit-zero",
            sql_path.to_str().unwrap(),
        ])
        .output()
        .expect("audit run");
    assert!(output.status.success(), "--exit-zero forces success");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("SC-SEC02"),
        "error-level finding must remain; got: {stdout}"
    );
    assert!(
        !stdout.contains("SC-SEC09"),
        "warn-level finding must be filtered out; got: {stdout}"
    );
}

#[test]
fn test_audit_dialect_flag_skips_pg_only_rule_on_sqlite() {
    let temp = tempfile::TempDir::new().unwrap();
    let sql_path = temp.path().join("set_role.sql");
    std::fs::write(&sql_path, "SET ROLE admin;\n").unwrap();

    let output = scythe_bin()
        .args([
            "audit",
            "--dialect",
            "sqlite",
            "--exit-zero",
            sql_path.to_str().unwrap(),
        ])
        .output()
        .expect("audit run");
    assert!(output.status.success(), "audit must exit 0");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        !stdout.contains("SC-SEC11"),
        "SC-SEC11 must not fire under --dialect sqlite; got: {stdout}"
    );
}
