//! Regression tests for issue #211: `scythe migrate` used to (1) overwrite
//! an existing `scythe.toml` with no backup at all, (2) write a `codegen:`
//! target that `scythe generate` then rejected as an unknown backend for a
//! non-Rust language, and (3) count files it did not actually change as
//! "converted".
//!
//! Every test drives the compiled binary via
//! `Command::new(env!("CARGO_BIN_EXE_scythe"))` with `.current_dir(...)` set
//! on the child process, following the idiom in `migrate_integration.rs`.

use std::process::{Command, Output};

use tempfile::TempDir;

fn scythe_bin() -> Command {
    Command::new(env!("CARGO_BIN_EXE_scythe"))
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

const SCHEMA_SQL: &str = "CREATE TABLE widgets (id bigint PRIMARY KEY, name text NOT NULL);\n";
const SQLC_QUERY_SQL: &str = "-- name: GetWidget :one\nSELECT id, name FROM widgets WHERE id = sqlc.arg(widget_id);\n";

/// #211, item 1: `migrate` must not destroy a hand-written `scythe.toml`
/// sitting at the destination -- it must back it up first, exactly like it
/// already does for converted query files (`.sql.bak`).
#[test]
fn migrate_backs_up_an_existing_scythe_toml_before_overwriting_it() {
    let project = TempDir::new().unwrap();
    std::fs::write(project.path().join("schema.sql"), SCHEMA_SQL).unwrap();
    std::fs::create_dir_all(project.path().join("queries")).unwrap();
    std::fs::write(project.path().join("queries/q.sql"), SQLC_QUERY_SQL).unwrap();

    let sqlc_config = "version: \"2\"\n\
         sql:\n\
         \x20 - engine: postgresql\n\
         \x20\x20\x20 schema: schema.sql\n\
         \x20\x20\x20 queries: queries\n\
         \x20\x20\x20 codegen:\n\
         \x20\x20\x20\x20\x20 - plugin: rust\n\
         \x20\x20\x20\x20\x20\x20\x20 out: generated\n";
    std::fs::write(project.path().join("sqlc.yaml"), sqlc_config).unwrap();

    let precious = "# PRECIOUS HAND-WRITTEN CONFIG -- do not clobber\n[scythe]\nversion = \"1\"\n";
    let scythe_toml = project.path().join("scythe.toml");
    std::fs::write(&scythe_toml, precious).unwrap();

    let output = scythe_bin()
        .args(["migrate", "sqlc.yaml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe migrate");

    assert!(
        output.status.success(),
        "migrate must succeed; stderr: {}",
        stderr(&output)
    );

    let bak_path = project.path().join("scythe.toml.bak");
    assert!(
        bak_path.exists(),
        "expected a scythe.toml.bak backup of the pre-existing config, none found"
    );
    let bak_content = std::fs::read_to_string(&bak_path).unwrap();
    assert_eq!(
        bak_content, precious,
        "the backup must preserve the original hand-written config verbatim"
    );

    // The live scythe.toml must have been regenerated (no longer the
    // precious hand-written content) -- migrate's whole point is to
    // convert, so overwriting is expected; only the *silent, unrecoverable*
    // loss is the bug.
    let live_content = std::fs::read_to_string(&scythe_toml).unwrap();
    assert_ne!(
        live_content, precious,
        "scythe.toml should have been regenerated by migrate"
    );
}

/// #211, item 1 (negative case): when no `scythe.toml` exists yet, migrate
/// must not create a spurious `.bak` file out of nothing.
#[test]
fn migrate_does_not_create_a_backup_when_no_scythe_toml_existed() {
    let project = TempDir::new().unwrap();
    std::fs::write(project.path().join("schema.sql"), SCHEMA_SQL).unwrap();
    std::fs::create_dir_all(project.path().join("queries")).unwrap();
    std::fs::write(project.path().join("queries/q.sql"), SQLC_QUERY_SQL).unwrap();

    let sqlc_config = "version: \"2\"\n\
         sql:\n\
         \x20 - engine: postgresql\n\
         \x20\x20\x20 schema: schema.sql\n\
         \x20\x20\x20 queries: queries\n\
         \x20\x20\x20 codegen:\n\
         \x20\x20\x20\x20\x20 - plugin: rust\n\
         \x20\x20\x20\x20\x20\x20\x20 out: generated\n";
    std::fs::write(project.path().join("sqlc.yaml"), sqlc_config).unwrap();

    let output = scythe_bin()
        .args(["migrate", "sqlc.yaml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe migrate");

    assert!(
        output.status.success(),
        "migrate must succeed; stderr: {}",
        stderr(&output)
    );
    assert!(
        !project.path().join("scythe.toml.bak").exists(),
        "no scythe.toml.bak should be created when there was nothing to back up"
    );
}

/// #211, item 2: a non-Rust `codegen:` plugin (`golang`, sqlc's real Go
/// plugin name) must migrate to a `scythe generate`-usable backend, not the
/// raw plugin name as a language key with a Rust driver default.
#[test]
fn migrate_maps_golang_codegen_plugin_to_a_working_go_backend() {
    let project = TempDir::new().unwrap();
    std::fs::write(project.path().join("schema.sql"), SCHEMA_SQL).unwrap();
    std::fs::create_dir_all(project.path().join("queries")).unwrap();
    std::fs::write(project.path().join("queries/q.sql"), SQLC_QUERY_SQL).unwrap();

    let sqlc_config = "version: \"2\"\n\
         sql:\n\
         \x20 - engine: postgresql\n\
         \x20\x20\x20 schema: schema.sql\n\
         \x20\x20\x20 queries: queries\n\
         \x20\x20\x20 codegen:\n\
         \x20\x20\x20\x20\x20 - plugin: golang\n\
         \x20\x20\x20\x20\x20\x20\x20 out: gen/go\n";
    std::fs::write(project.path().join("sqlc.yaml"), sqlc_config).unwrap();

    let migrate_output = scythe_bin()
        .args(["migrate", "sqlc.yaml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe migrate");
    assert!(
        migrate_output.status.success(),
        "migrate must succeed; stderr: {}",
        stderr(&migrate_output)
    );

    let scythe_toml = std::fs::read_to_string(project.path().join("scythe.toml")).unwrap();
    assert!(
        scythe_toml.contains("[sql.gen.go]"),
        "expected the codegen plugin normalized to the 'go' language key, got:\n{scythe_toml}"
    );
    assert!(
        !scythe_toml.contains("tokio-postgres"),
        "a Go target must never default to a Rust driver name, got:\n{scythe_toml}"
    );

    let generate_output = scythe_bin()
        .args(["generate", "--config", "scythe.toml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe generate");
    assert!(
        generate_output.status.success(),
        "scythe generate must accept the migrated config; stderr: {}",
        stderr(&generate_output)
    );
    assert!(
        project.path().join("gen/go/queries.go").exists(),
        "expected a generated queries.go under gen/go"
    );
}

/// #211, item 3: a query file with no `-- name:` annotations passes through
/// `migrate` unchanged and must not be counted as "converted".
#[test]
fn migrate_does_not_count_an_unchanged_file_as_converted() {
    let project = TempDir::new().unwrap();
    std::fs::write(project.path().join("schema.sql"), SCHEMA_SQL).unwrap();
    std::fs::create_dir_all(project.path().join("queries")).unwrap();
    // No `-- name:` annotation at all -- sqlc itself would also reject this
    // file, but `migrate`'s conversion pass must not claim to have done
    // anything to it.
    std::fs::write(
        project.path().join("queries/plain.sql"),
        "SELECT id, name FROM widgets WHERE id = $1;\n",
    )
    .unwrap();

    let sqlc_config = "version: \"2\"\n\
         sql:\n\
         \x20 - engine: postgresql\n\
         \x20\x20\x20 schema: schema.sql\n\
         \x20\x20\x20 queries: queries\n\
         \x20\x20\x20 codegen:\n\
         \x20\x20\x20\x20\x20 - plugin: rust\n\
         \x20\x20\x20\x20\x20\x20\x20 out: generated\n";
    std::fs::write(project.path().join("sqlc.yaml"), sqlc_config).unwrap();

    let output = scythe_bin()
        .args(["migrate", "sqlc.yaml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe migrate");

    assert!(
        output.status.success(),
        "migrate must succeed; stderr: {}",
        stderr(&output)
    );
    let out = stdout(&output);
    assert!(
        out.contains("0 file(s) converted"),
        "a file with no sqlc annotations must not be counted as converted; stdout: {out}"
    );
    assert!(
        !project.path().join("queries/plain.sql.bak").exists(),
        "an unchanged file must not get a .sql.bak either"
    );
}

/// #211, item 3 (positive case, for contrast): a file that *does* have a
/// convertible annotation is still counted, alongside the unconverted one.
#[test]
fn migrate_counts_only_the_file_it_actually_converted() {
    let project = TempDir::new().unwrap();
    std::fs::write(project.path().join("schema.sql"), SCHEMA_SQL).unwrap();
    std::fs::create_dir_all(project.path().join("queries")).unwrap();
    std::fs::write(project.path().join("queries/plain.sql"), "SELECT 1;\n").unwrap();
    std::fs::write(project.path().join("queries/q.sql"), SQLC_QUERY_SQL).unwrap();

    let sqlc_config = "version: \"2\"\n\
         sql:\n\
         \x20 - engine: postgresql\n\
         \x20\x20\x20 schema: schema.sql\n\
         \x20\x20\x20 queries: queries\n\
         \x20\x20\x20 codegen:\n\
         \x20\x20\x20\x20\x20 - plugin: rust\n\
         \x20\x20\x20\x20\x20\x20\x20 out: generated\n";
    std::fs::write(project.path().join("sqlc.yaml"), sqlc_config).unwrap();

    let output = scythe_bin()
        .args(["migrate", "sqlc.yaml"])
        .current_dir(project.path())
        .output()
        .expect("run scythe migrate");

    assert!(
        output.status.success(),
        "migrate must succeed; stderr: {}",
        stderr(&output)
    );
    let out = stdout(&output);
    assert!(
        out.contains("1 file(s) converted"),
        "exactly one of the two query files was actually convertible; stdout: {out}"
    );
    assert!(project.path().join("queries/q.sql.bak").exists());
    assert!(!project.path().join("queries/plain.sql.bak").exists());
}
