[scythe]
version = "1"

[[sql]]
name = "main"
engine = "oracle"
schema = ["../sql/oracle/schema.sql"]
queries = ["../sql/oracle/queries/*.sql"]

[[sql.gen]]
backend = "typescript-oracledb"
output = "generated"
