[scythe]
version = "1"

[[sql]]
name = "main"
engine = "sqlite"
schema = ["../sql/sqlite/schema.sql"]
queries = ["../sql/sqlite/queries/*.sql"]

[[sql.gen]]
backend = "php-pdo-sqlite"
output = "generated"
