//! Provenance rules (`SC-PRV*`) — schema-drift detection over *generated
//! artifacts*, not over SQL.
//!
//! Every rule in this module deliberately leaves both [`LintRule::check_query`]
//! and [`LintRule::check_catalog`] at their no-op defaults. There is nothing
//! for them to inspect here: the findings are produced by `scythe check`'s
//! artifact-verification pass, which reads the provenance header line out of
//! each already-generated file and compares it against the current catalog
//! fingerprint, engine, backend, and scythe version. A `LintContext` carries
//! none of that.
//!
//! They live in [`crate::registry::provenance_registry`], **not** in
//! [`crate::registry::default_registry`]. That separation is deliberate in
//! both directions:
//!
//! - Out of the default registry, because everything that consumes it —
//!   `scythe lint`, and `scythe audit --list-rules` via
//!   `load_registry_for_discovery` — evaluates rules through `check_query` /
//!   `check_catalog`. Listing eleven rules there that neither command can
//!   ever emit would advertise a capability that does not exist, and would
//!   move the documented "58 built-in rules" figure that appears across the
//!   README, the website, and the skills bundle.
//! - In a registry at all, rather than a bare list, because that is what
//!   makes them configurable. `scythe check` applies the same `[lint]` table
//!   to this registry that it applies to the default one, then resolves each
//!   severity through [`crate::registry::RuleRegistry::effective_severity`] —
//!   the same call every SQL rule's severity goes through. So
//!   `[lint.rules] "SC-PRV01" = "off"` and `[lint.categories] provenance =
//!   "off"` both work. Hardcoding the severities instead would leave schema
//!   drift as the one finding in scythe with no opt-out from failing CI —
//!   and it is the one finding that fires on a file the developer did not
//!   edit.

use crate::rule::LintRule;
use crate::types::{RuleCategory, Severity};

/// `SC-PRV01` — the artifact's embedded schema fingerprint differs from the
/// fingerprint of the schema currently on disk.
///
/// `Error` by default: this is the rule the whole provenance feature exists
/// for. A generated file compiled against a schema that no longer matches is
/// the failure the header was added to catch, and it is always fixable by
/// running `scythe generate`.
pub struct SchemaDrift;

impl LintRule for SchemaDrift {
    fn id(&self) -> &'static str {
        "SC-PRV01"
    }
    fn name(&self) -> &'static str {
        "schema-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced from a different schema than the one on disk"
    }
}

/// `SC-PRV02` — the artifact was generated by a different scythe version
/// than the one running.
///
/// `Warn` by default, and it must stay that way: scythe cutting a release is
/// not a defect in the consumer's project. Defaulting this to `Error` would
/// fail every consumer's CI on the day they bump scythe, before they have
/// had any chance to regenerate. Projects that want a hard gate can raise it
/// themselves via `[lint.rules]`.
pub struct ScytheVersionDrift;

impl LintRule for ScytheVersionDrift {
    fn id(&self) -> &'static str {
        "SC-PRV02"
    }
    fn name(&self) -> &'static str {
        "scythe-version-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Warn
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced by a different scythe version than the one running"
    }
}

/// `SC-PRV03` — the artifact was generated by a different backend than the
/// one this target now configures.
///
/// `Error` by default: the file on disk is the output of a backend nobody
/// asked for any more, so its API, imports, and driver calls are all wrong
/// for the configured target.
pub struct BackendDrift;

impl LintRule for BackendDrift {
    fn id(&self) -> &'static str {
        "SC-PRV03"
    }
    fn name(&self) -> &'static str {
        "backend-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced by a different backend than this target configures"
    }
}

/// `SC-PRV04` — the artifact was generated for a different engine than this
/// target now configures.
///
/// `Error` by default, for the same reason as [`BackendDrift`]: placeholder
/// syntax, quoting, and type mapping are all engine-specific, so the
/// committed file is wrong for the configured engine.
pub struct EngineDrift;

impl LintRule for EngineDrift {
    fn id(&self) -> &'static str {
        "SC-PRV04"
    }
    fn name(&self) -> &'static str {
        "engine-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced for a different engine than this target configures"
    }
}

/// `SC-PRV05` — the artifact carries no provenance header at all.
///
/// `Warn` by default: the most likely cause is a file generated before
/// provenance headers existed, or a file that was never scythe-managed. Both
/// are situations to flag, not to fail a build over — regenerating fixes it,
/// and nothing about the file is known to be wrong.
pub struct MissingProvenanceHeader;

impl LintRule for MissingProvenanceHeader {
    fn id(&self) -> &'static str {
        "SC-PRV05"
    }
    fn name(&self) -> &'static str {
        "missing-provenance-header"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Warn
    }
    fn description(&self) -> &'static str {
        "Generated artifact has no provenance header, so it cannot be checked for schema drift"
    }
}

/// `SC-PRV06` — a provenance header is present but is missing fields.
///
/// `Warn` by default: like [`MissingProvenanceHeader`], nothing is known to
/// be wrong with the file — only that it cannot be checked. Hand-editing or
/// a truncated write are the usual causes.
pub struct MalformedProvenanceHeader;

impl LintRule for MalformedProvenanceHeader {
    fn id(&self) -> &'static str {
        "SC-PRV06"
    }
    fn name(&self) -> &'static str {
        "malformed-provenance-header"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Warn
    }
    fn description(&self) -> &'static str {
        "Generated artifact's provenance header is missing one or more required fields"
    }
}

/// `SC-PRV07` — a generation target could not be verified at all: its
/// backend/engine pair does not construct, or its artifact could not be read
/// for a reason other than not existing.
///
/// `Warn` by default. It reports the *absence* of a verification result, not
/// a detected mismatch, and it exists so that absence is visible rather than
/// silent — but it must never be able to sink a `scythe check` run on its
/// own, because the underlying causes (a typo'd backend name, an engine a
/// backend does not support, a permissions problem in the output directory)
/// are already reported far more precisely by `scythe generate`.
pub struct UnverifiableProvenance;

impl LintRule for UnverifiableProvenance {
    fn id(&self) -> &'static str {
        "SC-PRV07"
    }
    fn name(&self) -> &'static str {
        "unverifiable-provenance"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Warn
    }
    fn description(&self) -> &'static str {
        "Generation target could not be verified: backend construction or artifact read failed"
    }
}

/// `SC-PRV08` — the artifact's embedded *query* fingerprint differs from the
/// fingerprint of the analyzed query set currently on disk.
///
/// A distinct finding from [`SchemaDrift`] (`SC-PRV01`), deliberately:
/// `SchemaDrift` answers "does this artifact match the current *schema*?"
/// and says nothing about the `.sql` query files that produced the
/// generated functions themselves. Editing a query without touching the
/// schema used to produce no drift signal at all -- this rule is what closes
/// that gap (#94).
///
/// `Error` by default, matching `SchemaDrift`: this is the same class of
/// failure (stale generated code, not merely stale metadata) and it is
/// always fixable by running `scythe generate`.
///
/// Only fires when the header actually carries a `queries=` field. A header
/// written by scythe 0.14.0 or earlier has no such field -- that reads as
/// "query drift is not covered for this artifact" (silently skipped), not
/// as drift. See `verify_artifact` in `scythe-cli` for where that
/// backward-compatibility decision is made.
pub struct QueryDrift;

impl LintRule for QueryDrift {
    fn id(&self) -> &'static str {
        "SC-PRV08"
    }
    fn name(&self) -> &'static str {
        "query-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced from a different analyzed query set than the one on disk"
    }
}

/// `SC-PRV09` — a `[[sql.gen]]` target in this block could not be
/// constructed: an unresolvable target, a backend/engine pair that will not
/// build, a manifest override or options that fail to apply, or an output
/// path that would escape the project root.
///
/// `Error` by default: a target `scythe generate` refuses to build cannot
/// have produced the artifact on disk, so there is nothing here for
/// provenance verification to compare against -- this rule reports the
/// misconfiguration itself, not drift.
///
/// Distinct from [`UnverifiableProvenance`] (`SC-PRV07`), which fires when
/// verification of an otherwise-valid target fails for a different reason
/// (e.g. the artifact file cannot be read). `SC-PRV09` fires earlier, before
/// there is a target to verify at all -- see `validate_gen_targets_constructible`
/// in `scythe-cli`, which mirrors `scythe generate`'s own construction steps
/// so `scythe check` reports precisely what `generate` would refuse.
pub struct GenTargetInvalid;

impl LintRule for GenTargetInvalid {
    fn id(&self) -> &'static str {
        "SC-PRV09"
    }
    fn name(&self) -> &'static str {
        "gen-target-invalid"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "A [[sql.gen]] target could not be constructed: unresolvable target, backend/engine that will not build, \
         manifest override or options that fail to apply, or an output path escaping the project root"
    }
}

/// `SC-PRV10` — a query file has content but produced zero `-- name:` /
/// `-- @name` query blocks, so nothing in it was checked.
///
/// `Error` by default: a mistyped annotation (`--name:` with no leading
/// space, a query commented out by hand, or a file whose annotations were
/// simply never recognised) silently drops every statement in the file from
/// generation, linting, and auditing alike, with no other signal that
/// anything was skipped.
pub struct EmptyQueryFile;

impl LintRule for EmptyQueryFile {
    fn id(&self) -> &'static str {
        "SC-PRV10"
    }
    fn name(&self) -> &'static str {
        "empty-query-file"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Query file has content but produced zero `-- name:` / `-- @name` query blocks; nothing in it was checked"
    }
}

/// `SC-PRV11` — the artifact was generated with different `[[sql.gen]]`
/// options (derive list, serde flag, `row_type`, naming case, ...), or a
/// different manifest overlay's *contents*, than this target now configures.
///
/// A distinct finding from [`BackendDrift`]/[`EngineDrift`] for the same
/// reason [`QueryDrift`] is distinct from [`SchemaDrift`]: the schema,
/// engine and backend can all still match while an *option* -- which
/// changes the generated code's derives, serde attributes, row type, or
/// naming convention just as much as a schema or engine change would --
/// silently drifted, and before this rule existed nothing detected that
/// (GH #155). See `scythe_codegen::provenance::options_fingerprint`
/// for what participates in the comparison and how it stays stable across
/// machines and runs.
///
/// `Error` by default, matching [`SchemaDrift`]/[`BackendDrift`]/
/// [`EngineDrift`]/[`QueryDrift`]: the file on disk is not what the current
/// config would produce, and it is always fixable by running `scythe
/// generate`.
pub struct OptionsDrift;

impl LintRule for OptionsDrift {
    fn id(&self) -> &'static str {
        "SC-PRV11"
    }
    fn name(&self) -> &'static str {
        "options-drift"
    }
    fn category(&self) -> RuleCategory {
        RuleCategory::Provenance
    }
    fn default_severity(&self) -> Severity {
        Severity::Error
    }
    fn description(&self) -> &'static str {
        "Generated artifact was produced with different [[sql.gen]] options (or manifest overlay contents) than \
         this target now configures"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The eleven provenance rules, in id order, as `&dyn LintRule`.
    fn all_rules() -> Vec<&'static dyn LintRule> {
        vec![
            &SchemaDrift as &dyn LintRule,
            &ScytheVersionDrift,
            &BackendDrift,
            &EngineDrift,
            &MissingProvenanceHeader,
            &MalformedProvenanceHeader,
            &UnverifiableProvenance,
            &QueryDrift,
            &GenTargetInvalid,
            &EmptyQueryFile,
            &OptionsDrift,
        ]
    }

    /// Unique, and in the fixed order this module declares them.
    #[test]
    fn ids_are_unique_and_in_declared_order() {
        let ids: Vec<&str> = all_rules().iter().map(|r| r.id()).collect();
        assert_eq!(
            ids,
            vec![
                "SC-PRV01", "SC-PRV02", "SC-PRV03", "SC-PRV04", "SC-PRV05", "SC-PRV06", "SC-PRV07", "SC-PRV08",
                "SC-PRV09", "SC-PRV10", "SC-PRV11"
            ]
        );
    }

    #[test]
    fn every_rule_is_in_the_provenance_category() {
        for rule in all_rules() {
            assert_eq!(rule.category(), RuleCategory::Provenance, "rule: {}", rule.id());
        }
    }

    /// Pins the default severities the rest of the toolchain reasons about:
    /// the drift rules (plus the two misconfiguration rules, which are
    /// equally always-fixable) fail a build, and everything that only
    /// reports "this could not be checked" (plus the scythe-version
    /// mismatch, see [`ScytheVersionDrift`]) warns.
    #[test]
    fn default_severities_are_error_only_for_real_drift() {
        assert_eq!(SchemaDrift.default_severity(), Severity::Error);
        assert_eq!(BackendDrift.default_severity(), Severity::Error);
        assert_eq!(EngineDrift.default_severity(), Severity::Error);
        assert_eq!(QueryDrift.default_severity(), Severity::Error);
        assert_eq!(GenTargetInvalid.default_severity(), Severity::Error);
        assert_eq!(EmptyQueryFile.default_severity(), Severity::Error);
        assert_eq!(OptionsDrift.default_severity(), Severity::Error);

        assert_eq!(
            ScytheVersionDrift.default_severity(),
            Severity::Warn,
            "a scythe upgrade must never fail a consumer's CI by default"
        );
        assert_eq!(MissingProvenanceHeader.default_severity(), Severity::Warn);
        assert_eq!(MalformedProvenanceHeader.default_severity(), Severity::Warn);
        assert_eq!(UnverifiableProvenance.default_severity(), Severity::Warn);
    }

    /// These rules are evaluated outside the `check_*` path; if one ever
    /// grows a real implementation, the artifact-verification pass in
    /// `scythe check` would start double-reporting it.
    #[test]
    fn no_provenance_rule_participates_in_the_check_query_path() {
        let catalog = scythe_core::catalog::Catalog::from_ddl(&["CREATE TABLE t (id INTEGER);"]).unwrap();
        for rule in all_rules() {
            assert!(
                rule.check_catalog(&catalog).is_empty(),
                "rule {} produced catalog violations; provenance findings must come from artifact verification",
                rule.id()
            );
        }
    }
}
