[scythe]
version = "1"

[[sql]]
name = "main"
engine = "oracle"
schema = ["../sql/oracle/schema_full.sql"]
queries = ["../sql/oracle/queries/*.sql"]

[[sql.gen]]
backend = "rust-sibyl"
output = "src"
structs_only = "true"
